;/*FB_PKG_DELIM*/

__d("LexicalComposer",["cr:427"],(function(t,n,r,o,a,i){a.exports=n("cr:427")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 *
 * @fullSyntaxTransform
 * @es6-async_DO_NOT_USE
 * @generated SignedSource<<1efa159b849e49ee6b79b7c0b020e315>>
 * 
 * @nolint
 * @oncall lexical_web_text_editor
 * @preserve-invariant-messages
 * @preserve-whitespace
 * @preventMunge
 */__d("LexicalComposer.prod",["Lexical","LexicalComposerContext","react"],(function $module_LexicalComposer_prod(global,require,requireDynamic,requireLazy,module,exports){

"use strict";var _require_closure_react;var o=_require_closure_react||(_require_closure_react=require("react")),r=_require_closure_react;var n=require("Lexical").CAN_USE_DOM?o.useLayoutEffect:o.useEffect,a={tag:require("Lexical").HISTORY_MERGE_TAG};exports.LexicalComposer=function(_ref){var i=_ref.initialConfig,c=_ref.children;var s=o.useMemo(function(){var o=i.theme,r=i.namespace,n=i.nodes,c=i.onError,s=i.onWarn,l=i.editorState,u=i.html,d=require("LexicalComposerContext").createLexicalComposerContext(null,o),E=require("Lexical").createEditor(babelHelpers["extends"]({editable:i.editable,html:u,namespace:r,nodes:n,onError:function onError(e){return c(e,E);}},s?{onWarn:function onWarn(e){return s(e,E);}}:{},{theme:o}));return function(e,o){if(null===o)return;if(void 0===o)e.update(function(){var o=require("Lexical").$getRoot();if(o.isEmpty()){var _r=require("Lexical").$createParagraphNode();o.append(_r);var _n=require("Lexical").CAN_USE_DOM?document.activeElement:null;(null!==require("Lexical").$getSelection()||null!==_n&&_n===e.getRootElement())&&_r.select();}},a);else if(null!==o)switch(typeof o){case"string":{var _t=e.parseEditorState(o);e.setEditorState(_t,a);break;}case"object":e.setEditorState(o,a);break;case"function":e.update(function(){require("Lexical").$getRoot().isEmpty()&&o(e);},a);}}(E,l),[E,d];},[]);return n(function(){var e=i.editable,t=s[0];t.setEditable(void 0===e||e);},[]),r.jsx(require("LexicalComposerContext").LexicalComposerContext.Provider,{value:s,children:c});};}),null);
__d("MLCMetadataContext.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useContext,d=u.useMemo,m=s.createContext({contentID:null,surface:null});function p(e){var t=e.children,n=e.contentID,r=e.surface,o=d(function(){return{contentID:n,surface:r}},[n,r]);return s.jsx(m.Provider,{value:o,children:t})}p.displayName=p.name+" [from "+i.id+"]";function _(){return c(m)}l.MLCMetadataProvider=p,l.useMLCMetadata=_}),98);
__d("MLCComposer.react",["FBLogger","LexicalComposer","MLCInstrumentationPluginDeferred__INTERNAL.react","MLCMetadataContext.react","mlcErrorHandler__INTERNAL","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=e.children,n=e.contentID,a=e.initialConfig,i=e.typingPerformanceID,l=a.editor,u=a.editorState,c=a.policyProduct,d=a.surface,m=babelHelpers.extends({},l,{editorState:u,namespace:d,onError:function(t,n){return r("mlcErrorHandler__INTERNAL")(t,n,function(e){l.onError(t,e,n)})},onWarn:function(t,n){return r("mlcErrorHandler__INTERNAL")(t,n,function(e){l.onWarn!=null?l.onWarn(t,e,n):r("FBLogger")("lexical").catching(t).addMetadata("LEXICAL","ERROR_INTERNAL",e).warn("Lexical editor warning on %s",d)})}});return s.jsxs(o("LexicalComposer").LexicalComposer,{initialConfig:m,children:[r("MLCInstrumentationPluginDeferred__INTERNAL.react")&&s.jsx(r("MLCInstrumentationPluginDeferred__INTERNAL.react"),{policyProduct:c,surface:d,typingPerformanceID:i}),s.jsx(o("MLCMetadataContext.react").MLCMetadataProvider,{contentID:n,surface:d,children:t})]})}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("MLCContentEditableCommands",["Lexical"],(function(t,n,r,o,a,i,l){"use strict";var e=o("Lexical").createCommand();l.MLC_EDITOR_ARIA_COMMAND=e}),98);
__d("MLCContentEditable.react",["cx","Lexical","LexicalComposerContext","LexicalContentEditable","MLCContentEditableCommands","joinClasses","react","stylex"],(function(t,n,r,o,a,i,l,s){"use strict";var e=["ariaAutoComplete","ariaDescribedBy","ariaErrorMessage","ariaExpanded","ariaInvalid","ariaLabel","ariaLabelledBy","ariaMultiline","ariaOwnerID","ariaRequired","autoCapitalize","autoComplete","autoCorrect","data-testid","id","readOnly","ref","role","spellCheck","tabIndex","xstyle"],u,c,d=c||(c=o("react")),m=c,p=m.useLayoutEffect,_=m.useState,f={editor:{color:"xzsf02u",overflowX:"xw2csxc",overflowY:"x1odjw0f",position:"x1n2onr6",tabSize:"x1hnll1o",":focus-visible_outline":"xpqswwc",$$css:!0}};function g(t){var n,a=t.ariaAutoComplete,i=t.ariaDescribedBy,l=t.ariaErrorMessage,s=t.ariaExpanded,c=t.ariaInvalid,m=t.ariaLabel,g=t.ariaLabelledBy,h=t.ariaMultiline,y=t.ariaOwnerID,C=t.ariaRequired,b=t.autoCapitalize,v=t.autoComplete,S=t.autoCorrect,R=t["data-testid"],L=R===void 0?"mlc-content-editable":R,E=t.id,k=t.readOnly,I=k===void 0?!1:k,T=t.ref,D=t.role,x=D===void 0?"textbox":D,$=t.spellCheck,P=$===void 0?!0:$,N=t.tabIndex,M=t.xstyle,w=babelHelpers.objectWithoutPropertiesLoose(t,e),A=o("LexicalComposerContext").useLexicalComposerContext(),F=A[0],O=_(!I),B=O[0],W=O[1],q=_(void 0),U=q[0],V=q[1],H=_(void 0),G=H[0],z=H[1];return p(function(){return W(F.isEditable()),F.registerEditableListener(W)},[F]),p(function(){return F.registerCommand(o("MLCContentEditableCommands").MLC_EDITOR_ARIA_COMMAND,function(e){return Object.prototype.hasOwnProperty.call(e,"activeDescendantID")&&V(e.activeDescendantID),Object.prototype.hasOwnProperty.call(e,"controlsID")&&z(e.controlsID),!1},o("Lexical").COMMAND_PRIORITY_EDITOR)},[F]),d.jsx(o("LexicalContentEditable").ContentEditable,babelHelpers.extends({ariaActiveDescendant:U!=null?U:void 0,ariaAutoComplete:a,ariaControls:G!=null?G:void 0,ariaDescribedBy:i,ariaErrorMessage:l,ariaExpanded:s,ariaInvalid:c,ariaLabel:(n=m==null?void 0:m.toString())!=null?n:void 0,ariaLabelledBy:g,ariaMultiline:h,ariaOwns:y,ariaRequired:C!=null?C:void 0,autoCapitalize:b,autoComplete:v,autoCorrect:S,className:r("joinClasses")((u||(u=r("stylex")))(f.editor,M),B?"notranslate":""),"data-testid":void 0,id:E,role:x},w,{ref:T,spellCheck:P,suppressContentEditableWarning:!0,tabIndex:N}))}g.displayName=g.name+" [from "+i.id+"]",l.default=g}),98);
__d("MLCFocusPlugin.react",["Lexical","LexicalComposerContext","LexicalUtils","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useEffect,c=s.useImperativeHandle;function d(e){var t=e.onBlur,n=e.onEscape,r=e.onFocus,a=e.ref,i=o("LexicalComposerContext").useLexicalComposerContext(),l=i[0];return c(a,function(){return{focus:function(){return l.focus()},blur:function(){return l.blur()}}}),u(function(){var e;return o("LexicalUtils").mergeRegister(l.registerCommand((e=o("Lexical")).BLUR_COMMAND,function(e){return t!=null&&t(e),!1},e.COMMAND_PRIORITY_LOW),l.registerCommand(e.FOCUS_COMMAND,function(e){return r!=null&&r(e),!1},e.COMMAND_PRIORITY_LOW),l.registerCommand(e.KEY_ESCAPE_COMMAND,function(e){return n!=null&&n(e),!1},e.COMMAND_PRIORITY_LOW))},[l,t,n,r]),null}l.default=d}),98);
__d("MLCHistoryPlugin.react",["LexicalHistoryPlugin","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.createContext,d=u.useContext,m=u.useMemo,p=c({historyState:void 0});function _(){return d(p)}function f(e){var t=e.children,n=m(function(){return{historyState:o("LexicalHistoryPlugin").createEmptyHistoryState()}},[]);return s.jsx(p.Provider,{value:n,children:t})}f.displayName=f.name+" [from "+i.id+"]";function g(){var e=_(),t=e.historyState;return s.jsx(o("LexicalHistoryPlugin").HistoryPlugin,{externalHistoryState:t})}g.displayName=g.name+" [from "+i.id+"]",l.SharedHistoryContext=f,l.MLCHistoryPlugin=g}),98);
__d("PolarisNotesStrings",["fbt"],(function(t,n,r,o,a,i,l,s){"use strict";var e=s._(/*BTDS*/"followers you follow back"),u=s._(/*BTDS*/"Followers you follow back"),c=s._(/*BTDS*/"Close Friends"),d=s._(/*BTDS*/"Meta employees only"),m=s._(/*BTDS*/"Meta Internal"),p=s._(/*BTDS*/"Share a thought..."),_=s._(/*BTDS*/"Leave a new note"),f=s._(/*BTDS*/"Delete note"),g=s._(/*BTDS*/"Send message"),h=s._(/*BTDS*/"Note shared"),y=s._(/*BTDS*/"Couldn\u2019t share note. Try again."),C=s._(/*BTDS*/"Couldn\u2019t delete note. Try again."),b=s._(/*BTDS*/"Message not sent. Try again.");l.MUTUAL_FOLLOWS_AUDIENCE_TEXT=e,l.MUTUAL_FOLLOWS_AUDIENCE_OPTION_TEXT=u,l.CLOSE_FRIENDS_AUDIENCE_OPTION_TEXT=c,l.INTERNAL_AUDIENCE_TEXT=d,l.INTERNAL_AUDIENCE_OPTION_TEXT=m,l.COMPOSER_PLACEHOLDER_TEXT=p,l.LEAVE_A_NEW_NOTE=_,l.DELETE_NOTE=f,l.SEND_MESSAGE_PLACEHOLDER=g,l.NOTE_SHARED_TEXT=h,l.NOTE_NOT_SHARED_TEXT=y,l.NOTE_NOT_DELETED_TEXT=C,l.NOTE_REPLY_NOT_SENT_TEXT=b}),226);
__d("getNotesAudienceStrings",["PolarisNotesStrings","PolarisNotesTypes"],(function(t,n,r,o,a,i,l){"use strict";function e(e){switch(e){case o("PolarisNotesTypes").NoteAudienceOptionValues.MUTUAL_FOLLOWS:return o("PolarisNotesStrings").MUTUAL_FOLLOWS_AUDIENCE_OPTION_TEXT;case o("PolarisNotesTypes").NoteAudienceOptionValues.BESTIES:return o("PolarisNotesStrings").CLOSE_FRIENDS_AUDIENCE_OPTION_TEXT;case o("PolarisNotesTypes").NoteAudienceOptionValues.INTERNAL:return o("PolarisNotesStrings").INTERNAL_AUDIENCE_OPTION_TEXT}}function s(e){switch(e){case o("PolarisNotesTypes").NoteAudienceOptionValues.MUTUAL_FOLLOWS:return o("PolarisNotesStrings").MUTUAL_FOLLOWS_AUDIENCE_TEXT;case o("PolarisNotesTypes").NoteAudienceOptionValues.BESTIES:return o("PolarisNotesStrings").CLOSE_FRIENDS_AUDIENCE_OPTION_TEXT;case o("PolarisNotesTypes").NoteAudienceOptionValues.INTERNAL:return o("PolarisNotesStrings").INTERNAL_AUDIENCE_TEXT}}l.getNoteAudienceOptionString=e,l.getComposerSharedWithNoteAudienceString=s}),98);
__d("usePolarisLexicalEmojiButton",["Lexical","LexicalComposerContext","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useCallback;function u(e){var t=o("react-compiler-runtime").c(3),n=o("LexicalComposerContext").useLexicalComposerContext(),r=n[0],a;return t[0]!==r||t[1]!==e?(a=function(n){r.update(function(){o("Lexical").$insertNodes([o("Lexical").$createTextNode(n)])}),e==null||e()},t[0]=r,t[1]=e,t[2]=a):a=t[2],a}l.default=u}),98);
__d("usePolarisNoteToast",["IGDSButton.react","PolarisGenericStrings","react","react-compiler-runtime","useIGDSToaster"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e.useCallback;function c(){var e=o("react-compiler-runtime").c(3),t=r("useIGDSToaster")(),n=t.add,a=t.clear,i;return e[0]!==a||e[1]!==n?(i=function(t){n({actionComponent:s.jsx(r("IGDSButton.react"),{display:"block",label:o("PolarisGenericStrings").DISMISS_TEXT,onClick:a,variant:"primary_link"}),message:t,target:"bottom-left"})},e[0]=a,e[1]=n,e[2]=i):i=e[2],i}l.default=c}),98);