(function(g){var window=this;'use strict';var aE=function(A,P){if(!Number.isFinite(A))return String(A);A=String(A);var D=A.indexOf(".");D===-1&&(D=A.length);var d=A[0]==="-"?"-":"";d&&(A=A.substring(1));P="0".repeat(Math.max(0,P-D));return d+P+A},w0=function(A){typeof A==="number"?(this.date=Nyt(A,0,1),RE(this,1)):g.O8(A)?(this.date=Nyt(A.getFullYear(),A.getMonth(),A.getDate()),RE(this,A.getDate())):(this.date=new Date(g.E8()),A=this.date.getDate(),this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),
RE(this,A))},Nyt=function(A,P,D){P=new Date(A,P,D);
A>=0&&A<100&&P.setFullYear(P.getFullYear()-1900);return P},RE=function(A,P){A.getDate()!=P&&A.date.setUTCHours(A.date.getUTCHours()+(A.getDate()<P?1:-1))},xL=function(A){if(A.toggleButtonRenderer){var P=A.toggleButtonRenderer;
if(P.isToggled){var D=P.toggledText?g.fK(P.toggledText):"";A.update({text:D,icon:Tyb(P.toggledIcon)})}else D=P.defaultText?g.fK(P.defaultText):"",A.update({text:D,icon:Tyb(P.defaultIcon)});A.show()}else A.hide()},SnA=function(A,P){!A.toggleButtonRenderer&&P&&P.toggleButtonRenderer?A.toggleButtonRenderer=P.toggleButtonRenderer:P&&P.toggleButtonRenderer||(A.toggleButtonRenderer=null);
xL(A)},Tyb=function(A){if(!A)return null;
switch(A.iconType){case "NOTIFICATIONS":return{C:"svg",W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{C:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]};case "NOTIFICATIONS_NONE":return{C:"svg",W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},S:[{C:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]};
case "NOTIFICATIONS_ACTIVE":return g.wsW();default:return null}},sty=function(A,P){var D=g.C(P,JsA),d=g.C(P,L8t);
if(P&&(D||d)){if(D){var u=D;var B="notification/add_upcoming_event_reminder"}else d&&(u=d,B="notification/remove_upcoming_event_reminder");B&&u&&u.params&&qnJ(A,B,u.params)}},qnJ=function(A,P,D){var d=A.K.G();
A.O||(A.O=new g.D9(d.Mp));var u={context:g.HH(A.O.config_||g.im())};g.i2()&&(u.context.clientScreenNonce=g.i2());u.params=D;D={timeout:5E3,onError:()=>{W81(A)},
onTimeout:()=>{W81(A)}};
d.EC().O.tG(g.sEJ)&&(D.onSuccess=B=>{if(B=B.actions)for(let U of B)g.pc(A.K,"innertubeCommand",U)});
g.ZS(A.O,P,u,D)},W81=function(A){A.toggleButtonRenderer&&(A.toggleButtonRenderer.isToggled=!A.toggleButtonRenderer.isToggled,xL(A))},hR=function(A,P,D){if(P){var d=P.subtitleText!=null?g.fK(P.subtitleText):"";
D=D?D:P.mainText!=null?g.fK(P.mainText):"";A.update({mainText:D,subtitleText:d,label:P.mainText?.accessibility?.accessibilityData?.label??D});g.Cp(A.element,"ytp-offline-slate-single-text-line",!d);g.Cp(A.N,"ytp-offline-slate-bar-hidden",!D&&!d)}},fxx=function(A){try{let P=JSON.parse(A);
return P!=null?P:void 0}catch(P){}},uJ1=async function(A){var P=A.player.G(),D=A.getVideoData();
GB(A)&&(Ayq(A)?PBK(A,P,D):(D2q(A),await d2x(A,P,D)))},D2q=function(A){var P=A.getVideoData();
if(P.th)if(P.B("use_rta_for_player"))A.attestationResponse=BdP(A);else{let B=new g.tyt(P);if(g.pH.isInitialized()||A.sequenceNumber>=3){P=Promise;var D=P.resolve;let U=null;if(B.videoData.PR){var d=g.iTF(B);if(d){U={};let c={};d=d.split("&");for(u of d)d=u.split("="),d.length===2&&(c[d[0]]=d[1]);var u=c;u.r1a&&(U.webResponse=u.r1a);u.r1c&&(U.error=U2T[Number(u.r1c)]);U.challenge=B.videoData.PR}}A.attestationResponse=D.call(P,U||void 0)}}},iVt=function(A){var P=A.getVideoData(),D=A.player.G();
if(P.isLivePlayback)if(g.K3(D.j)){A.D=!0;A.L=!0;if(!g.L2(D)||g.Se(D))A.offlineSlate=new cyq(A.player),g.V(A,A.offlineSlate),g.Jg(A.player,A.offlineSlate.element,4);(P=P.getPlayerResponse())&&P.playabilityStatus&&(A.O=P.playabilityStatus);A.O?.status!=="UNPLAYABLE"&&(A.O?(P=e7T(void 0,A.O.liveStreamability&&A.O.liveStreamability.liveStreamabilityRenderer))?IE(A,P):IE(A,7500):IE(A,1E3))}else A.player.po("html5.unsupportedlive",2,"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else g.$t(P.Va,"heartbeat")&&
A.player.jV("heartbeat",A.getPlayerType())},gDy=function(A,P,D){var d=D.liveStreamability&&D.liveStreamability.liveStreamabilityRenderer,u=!(!d||!(d.switchStreamsImmediately||d.transitionTiming&&d.transitionTiming==="STREAM_TRANSITION_TIMING_IMMEDIATELY"));
P=e7T(P,d);var B=A.getVideoData(),U=A.player.getPlayerStateObject(A.getPlayerType()),c=U.isPlaying()&&!g.ct(B)&&!A.player.isAtLiveHead(A.getPlayerType());if(B.G().eZ()){var e=A.player.gI()?.OB()||{};e.status=D.status||"";e.dvr=`${+c}`;e["switch"]=`${+u}`;e.ended=`${+!(!d||!d.displayEndscreen)}`;A.player.F9("heartbeat",e)}e=d&&d.broadcastId;var H=A.O&&A.O.liveStreamability&&A.O.liveStreamability.liveStreamabilityRenderer&&A.O.liveStreamability.liveStreamabilityRenderer.broadcastId,k=e!==H&&e!=null;
k&&A.player.F9("lbidh",{broadcastId:e},!0);if(g.L2(B.G())&&d&&d.streamTransitionEndpoint){var l=g.C(d.streamTransitionEndpoint,g.X8)?.commands||[];for(var Q of l)if(g.C(Q,g.DK)?.signal==="RELOAD_PLAYER"){A.player.po("qoe.restart",0,void 0,"sa.reload","7");break}}Q=A.player.B("always_cache_redirect_endpoint");if(c&&!u&&!Q)return P;l=d&&d.streamTransitionEndpoint&&g.C(d.streamTransitionEndpoint,g.XY);if((d&&d.transitionTiming)==="STREAM_TRANSITION_TIMING_AT_STREAM_END")A.getVideoData().transitionEndpointAtEndOfStream=
l;else{if(l&&HVy(A,l,D))return P;Q&&!l&&A.getVideoData().transitionEndpointAtEndOfStream&&(A.getVideoData().transitionEndpointAtEndOfStream=void 0)}if(c&&!u&&Q)return P;if(D.status.toUpperCase()==="OK"){if(!g.jj(B)||k)return d={video_id:B.videoId},B.ue&&(d.is_live_destination="1"),d.disable_watch_next=!0,d.raw_watch_next_response=B.getWatchNextResponse(),d.autonav_state=B.autonavState,d.oauth_token=B.oauthToken,d.xH=B.xH,B.eC&&(d.vss_credentials_token=B.eC,d.vss_credentials_token_type=B.dn),B.Hy&&
(d.vvt=B.Hy),u=void 0,g.jj(B)?k&&(u=new $2J("broadcastIdChanged",`${H},${e}`),A.c9("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",D)):(e&&(u=new $2J("formatsReceived",`${e}`)),A.c9("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",D)),k&&A.player.F9("lbidr",{broadcastId:e}),A.player.loadVideoByPlayerVars(d,void 0,void 0,void 0,u),P;A.player.jV("heartbeat",A.getPlayerType())}d&&d.displayEndscreen&&(A.offlineSlate?
(A=A.offlineSlate,A.U=!0,A.uf&&A.api.mY()):U.isBuffering()&&(B=A.player.gI()?.OB()||{},A.player.F9("hbse",B,!0),A.player.mY(!0,"h"),g.pc(A.player,"onLiveMediaEnded",D)));return P},kib=function(A){var P=A.getVideoData();
!P.B("use_rta_for_player")&&P.th&&(P=P.botguardData)&&g.MN(P,A.player.G())},pq=function(A){A.A=0;
A.Y.stop();A.j=!1;A.sequenceNumber=0},BdP=async function(A){if(await g.In4())return A=A.getVideoData(),g.G09({cpn:A.clientPlaybackNonce,
encryptedVideoId:A.videoId||""},1500);if(A.sequenceNumber>=3)return{error:"ATTESTATION_ERROR_VM_INTERNAL_ERROR"}},VD=function(A){return A.player.G().experiments.EC().O.tG(g.ib)?A.heartbeatParams?.interval?A.heartbeatParams.interval*1E3:A.getVideoData().OF:2E3},IE=function(A,P){if(!A.Y.isActive()&&A.L){var D=A.getVideoData();
if(jt(A)||D.isLivePlayback)P===void 0&&(P=A.j?A.D?7500:A.heartbeatParams?.interval?A.heartbeatParams.interval*1E3:A.getVideoData().OF||6E4:1E3),A.Y.start(P)}},Ayq=function(A){var P=A.getVideoData();
if(!g.dI(A.getVideoData())||P.H0)return!1;if(P.j){A=P.j.flavor==="playready";let D=P.j.flavor==="widevine"&&P.B("html5_innertube_heartbeats_for_widevine");P=g.i7(P.j)&&P.B("html5_innertube_heartbeats_for_fairplay");return!(A||D||P)}return!0},jt=function(A){if(Ayq(A))return!!A.heartbeatParams;
var P=A.getVideoData();return!g.dI(A.getVideoData())||P.zM||P.pw?!!P.heartbeatToken:!1},vDt=function(A,P,D){P.vC&&(D=g.nS(D,{internalipoverride:P.vC}));
var d={cpn:P.clientPlaybackNonce};P.contextParams&&(d.context_params=P.contextParams);P.Md&&(d.kpt=P.Md);D=g.nS(D,d);g.Xp(D,{format:"RAW",method:"GET",timeout:3E4,onSuccess:u=>{if(!A.Y.isActive()&&GB(A)){A.U.reset();A.sequenceNumber++;u=u.responseText;var B=fxx(u);if(B){g.pc(A.player,"onHeartbeat",B);var U=B.status==="ok"?B.stop_heartbeat?2:0:B.status==="stop"?1:B.status==="live_stream_offline"?0:-1}else U=(U=u.match(lsP))?U[1]==="0"?0:1:-1;QmR(A,void 0,B,u,U)}},
onError:u=>{GB(A)&&MG(A,!0,`net-${u.status}`)},
onTimeout:()=>{GB(A)&&MG(A,!0,"timeout")},
withCredentials:!0})},GB=function(A){var P=A.getVideoData();
return A.player.getPresentingPlayerType()===3||!A.player.G().experiments.EC().O.tG(g.bjK)&&A.player.getPlayerStateObject(A.getPlayerType()).O(4)?!1:jt(A)||P.isLivePlayback?!0:(pq(A),!1)},PBK=function(A,P,D){if(A.heartbeatParams?.url){var d=g.nS(A.heartbeatParams.url,{request_id:g.dR9()});
D.Hy&&(d=g.nS(d,{vvt:D.Hy}),D.mdxEnvironment&&(d=g.nS(d,{mdx_environment:D.mdxEnvironment})));g.SC(P,D.oauthToken).then(u=>{u&&(d=g.nS(d,{access_token:u}));vDt(A,D,d)})}},d2x=async function(A,P,D){var d={videoId:D.videoId,
sequenceNumber:A.sequenceNumber,heartbeatServerData:A.hG??D.heartbeatServerData};A.Z=A.attestationResponse;D.th&&(d.attestationResponse=await A.Z);var u=g.xA(D),B=u.client??{};B.utcOffsetMinutes=A.utcOffsetMinutes;d.context=u;d.cpn=D.clientPlaybackNonce;if(u=typeof Intl!=="undefined"?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)B.timeZone=u;B={heartbeatChecks:[]};if(u=D.getPlayerResponse())D.heartbeatToken&&(d.heartbeatToken=D.heartbeatToken),(u=u.playabilityStatus)&&(u=u.liveStreamability)&&
u.liveStreamabilityRenderer&&B.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");D.heartbeatToken&&B.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.Se(P)){B.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var U=Kty(A);u={};U!==null&&(u.clientPlayerPositionUtcMillis=U);U=A.player.qs()?.JC()?.xP()||0;U>0&&(u.freePreviewWatchedDuration={seconds:`${U}`});B.unpluggedParams=u}d.heartbeatRequestParams=B;D.isLivePlayback?(B=Kty(A),B!==null&&(d.playbackState||(d.playbackState={}),
d.playbackState.playbackPosition={utcTimeMillis:B})):P.B("enable_heartbeat_vod_playback_position")&&(B=t2x(A),B!==null&&(d.playbackState||(d.playbackState={}),d.playbackState.playbackPosition={streamTimeMillis:B}));A.player.publish("heartbeatRequest",d);var c={timeout:3E4,onSuccess:e=>{if(!A.Y.isActive()&&GB(A)){var H=A.getVideoData(),k=H.th&&A.Z==null;H.th=!!e.heartbeatAttestationConfig?.requiresAttestation||k;k=e.playabilityStatus;var l=JSON.stringify(k)||"{}";e.authenticationMismatch&&A.player.F9("authshear",
{});var Q=-1;var v=e.playabilityStatus;v&&(g.pc(A.player,"onHeartbeat",v),v.status==="OK"?Q=e.stopHeartbeat?2:0:v.status==="UNPLAYABLE"?Q=1:v.status==="LIVE_STREAM_OFFLINE"&&(Q=0));A.sequenceNumber&&Q===-1||A.U.reset();A.sequenceNumber++;e.heartbeatServerData&&(A.hG=e.heartbeatServerData);H.rJ=e;(v=e.playerCueRangeSet)&&g.n$(H,v);e.playerCueRanges&&e.playerCueRanges.length>0&&(H.cueRanges=e.playerCueRanges);e.progressBarConfig?.progressBarStartPosition&&e.progressBarConfig?.progressBarEndPosition&&
(H.progressBarStartPosition=e.progressBarConfig.progressBarStartPosition,H.progressBarEndPosition=e.progressBarConfig.progressBarEndPosition);H.compositeLiveIngestionOffsetToken=e.compositeLiveIngestionOffsetToken;e.compositeLiveStatusToken!==H.compositeLiveStatusToken&&(H.compositeLiveStatusToken=e.compositeLiveStatusToken);H.heartbeatLoggingToken=e.heartbeatLoggingToken;H.publish("dataupdated");QmR(A,e,k,l,Q)}},
onError:e=>{GB(A)&&MG(A,!0,`net-${e.status}`)},
onTimeout:()=>{GB(A)&&MG(A,!0,"timeout")}};
g.SC(P,D.U()).then(e=>{e&&(c.oS=`Bearer ${e}`);g.ZS(A.Hy,"player/heartbeat",d,c)})},Kty=function(A){return(A=A.player.getProgressState(A.getPlayerType()).ingestionTime)&&isFinite(A)?`${Math.floor(A*1E3)}`:null},t2x=function(A){return(A=A.player.getCurrentTime({playerType:A.getPlayerType()}))&&isFinite(A)?`${Math.floor(A*1E3)}`:null},QmR=function(A,P,D,d,u){u===-1?(D=`decode ${g.j_(d,3)}`,MG(A,!1,D)):u===2?(pq(A),A.j=!0):(A.A=0,A.Y.stop(),u===1?(A.j=!1,D&&D.errorCode==="PLAYABILITY_ERROR_CODE_EMBARGOED"&&
A.player.Mh(!0),u=`pe.${D?.errorCode};ps.${D?.status}`,A.player.po("heartbeat.stop",2,A.m4(d),u),g.dL("heartbeatActionPlayerHalted",yyy(D)),P?.videoTransitionEndpoint&&D&&(P=P.videoTransitionEndpoint,(d=g.C(P,g.XY))&&HVy(A,d,D,{itct:P?.clickTrackingParams}))):(A.j=!0,d=0,A.D&&D&&(d=gDy(A,P,D),A.player.publish("livestatedata",D)),d?IE(A,d):IE(A)))},MG=function(A,P,D){if(!A.Y.isActive()){A.Y.stop();
A.A++;var d=P?"heartbeat.net":"heartbeat.servererror";{let B=A.getVideoData();if(B.wm||P&&!g.dI(A.getVideoData())&&!jt(A)&&B.isLivePlayback)var u=!1;else A.heartbeatParams?.retries?u=A.heartbeatParams.retries:u=B.Es||5,u=A.A>=u}u?(g.dL("heartbeatActionPlayerHalted",P?{enforcedPolicyToHaltOnNetworkFailure:!0}:yyy()),(P=A.getVideoData())&&P.isLivePlayback?A.player.po(d,1,"Video playback interrupted. Please try again.",D):A.player.po(d,1,"Sorry, there was an error licensing this video.",D)):(IE(A,A.U.getValue()),
g.Q3(A.U))}},yyy=function(A){var P={enforcedPolicyToHaltOnNetworkFailure:!1};
A&&(P.serializedServerContext=A.additionalLoggingData);return P},e7T=function(A,P){return(A=Number(A?.pollDelayMs))?A:(P=Number(P?.pollDelayMs))?P:0},HVy=function(A,P,D,d){var u=P&&P.videoId;
return u?(A.player.Iw(u,{autonav:"1",...(d||{})},void 0,!0,!0,P,A.getVideoData().U()),A.c9("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",D),!0):!1},asq={ERAS:["BC",
"AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),
WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y",
"MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss\u202fa zzzz","h:mm:ss\u202fa z","h:mm:ss\u202fa","h:mm\u202fa"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5},X7=asq;X7=asq;
var U2T=["ATTESTATION_ERROR_UNKNOWN","ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],R7F={300:"STREAMING_DEVICES_QUOTA_PER_24H_EXCEEDED",301:"ALREADY_PINNED_ON_A_DEVICE",303:"STOPPED_BY_ANOTHER_PLAYBACK",304:"TOO_MANY_STREAMS_PER_USER",305:"TOO_MANY_STREAMS_PER_ENTITLEMENT",400:"VIDEO_NOT_FOUND",401:"GEO_FAILURE",402:"STREAMING_NOT_ALLOWED",403:"UNSUPPORTED_DEVICE",405:"VIDEO_FORBIDDEN",500:"PURCHASE_NOT_FOUND",
501:"RENTAL_EXPIRED",502:"PURCHASE_REFUNDED",5E3:"BAD_REQUEST",5001:"CGI_PARAMS_MISSING",5002:"CGI_PARAMS_MALFORMED",5100:"AUTHENTICATION_MISSING",5101:"AUTHENTICATION_MALFORMED",5102:"AUTHENTICATION_EXPIRED",5200:"CAST_TOKEN_MALFORMED",5201:"CAST_TOKEN_EXPIRED",5202:"CAST_TOKEN_FAILED",5203:"CAST_SESSION_VIDEO_MISMATCHED",5204:"CAST_SESSION_DEVICE_MISMATCHED",6E3:"INVALID_DRM_MESSAGE",7E3:"SERVER_ERROR",8E3:"RETRYABLE_ERROR"};g.I=w0.prototype;g.I.SM=X7.FIRSTDAYOFWEEK;g.I.z_=X7.FIRSTWEEKCUTOFFDAY;
g.I.clone=function(){var A=new w0(this.date);A.SM=this.SM;A.z_=this.z_;return A};
g.I.getFullYear=function(){return this.date.getFullYear()};
g.I.getYear=function(){return this.getFullYear()};
g.I.getMonth=function(){return this.date.getMonth()};
g.I.getDate=function(){return this.date.getDate()};
g.I.getTime=function(){return this.date.getTime()};
g.I.getDay=function(){return this.date.getDay()};
g.I.getUTCFullYear=function(){return this.date.getUTCFullYear()};
g.I.getUTCMonth=function(){return this.date.getUTCMonth()};
g.I.getUTCDate=function(){return this.date.getUTCDate()};
g.I.getUTCDay=function(){return this.date.getDay()};
g.I.getUTCHours=function(){return this.date.getUTCHours()};
g.I.getUTCMinutes=function(){return this.date.getUTCMinutes()};
g.I.getTimezoneOffset=function(){return this.date.getTimezoneOffset()};
g.I.set=function(A){this.date=new Date(A.getFullYear(),A.getMonth(),A.getDate())};
g.I.setFullYear=function(A){this.date.setFullYear(A)};
g.I.setYear=function(A){this.setFullYear(A)};
g.I.setMonth=function(A){this.date.setMonth(A)};
g.I.setDate=function(A){this.date.setDate(A)};
g.I.setTime=function(A){this.date.setTime(A)};
g.I.setUTCFullYear=function(A){this.date.setUTCFullYear(A)};
g.I.setUTCMonth=function(A){this.date.setUTCMonth(A)};
g.I.setUTCDate=function(A){this.date.setUTCDate(A)};
g.I.add=function(A){if(A.years||A.months){var P=this.getMonth()+A.months+A.years*12,D=this.getYear()+Math.floor(P/12);P%=12;P<0&&(P+=12);a:{switch(P){case 1:var d=D%4!=0||D%100==0&&D%400!=0?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.setDate(1);this.setFullYear(D);this.setMonth(P);this.setDate(d)}A.days&&(D=this.getYear(),P=D>=0&&D<=99?-1900:0,A=new Date((new Date(D,this.getMonth(),this.getDate(),12)).getTime()+A.days*864E5),this.setDate(1),this.setFullYear(A.getFullYear()+
P),this.setMonth(A.getMonth()),this.setDate(A.getDate()),RE(this,A.getDate()))};
g.I.equals=function(A){return!(!A||this.getYear()!=A.getYear()||this.getMonth()!=A.getMonth()||this.getDate()!=A.getDate())};
g.I.toString=function(){var A=this.getFullYear(),P=A<0?"-":A>=1E4?"+":"";return[P+aE(Math.abs(A),P?6:4),aE(this.getMonth()+1,2),aE(this.getDate(),2)].join("")+""};
g.I.valueOf=function(){return this.date.valueOf()};var JsA=new g.f("addUpcomingEventReminderEndpoint");var L8t=new g.f("removeUpcomingEventReminderEndpoint");var wsJ=class extends g.W{constructor(A){super({C:"div",S:[{C:"button",rM:["ytp-offline-slate-button","ytp-button"],S:[{C:"div",J:"ytp-offline-slate-button-icon",R2:"{{icon}}"},{C:"div",J:"ytp-offline-slate-button-text",R2:"{{text}}"}]}]});this.K=A;this.O=this.toggleButtonRenderer=null;(this.Y=this.jH("ytp-offline-slate-button"))&&this.V(this.Y,"click",this.N);this.hide()}N(){if(this.toggleButtonRenderer){let A=this.toggleButtonRenderer;A.isToggled?sty(this,A.toggledServiceEndpoint):sty(this,A.defaultServiceEndpoint);
A.isToggled=!A.isToggled;xL(this)}}};var cyq=class extends g.W{constructor(A){super({C:"div",J:"ytp-offline-slate",S:[{C:"div",J:"ytp-offline-slate-background"},{C:"div",J:"ytp-offline-slate-bar",S:[{C:"span",J:"ytp-offline-slate-icon",S:[{C:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},S:[{C:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{C:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{C:"span",J:"ytp-offline-slate-messages",S:[{C:"div",J:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},R2:"{{mainText}}"},{C:"div",J:"ytp-offline-slate-subtitle-text",R2:"{{subtitleText}}"}]},{C:"span",J:"ytp-offline-slate-buttons"}]},{C:"button",rM:["ytp-offline-slate-close-button","ytp-button"],S:[g.d2()]},{C:"button",rM:["ytp-offline-slate-open-button","ytp-button"],S:[g.Dg()]}]});this.api=A;this.O=this.Y=null;this.background=this.jH("ytp-offline-slate-background");
this.N=this.jH("ytp-offline-slate-bar");this.j=new g.jp(()=>{g.mR(this.N,"ytp-offline-slate-bar-fade")},15E3);
this.U=!1;this.D=new g.jp(()=>{g.mR(this.element,"ytp-offline-slate-collapsed")},15E3);
g.V(this,this.D);g.V(this,this.j);this.countdownTimer=new g.jp(this.L,1E3,this);this.V(A,"presentingplayerstatechange",this.A);this.V(A,"livestatedata",this.dM);this.V(this.jH("ytp-offline-slate-close-button"),"click",()=>{g.mR(this.element,"ytp-offline-slate-collapsed")});
this.V(this.jH("ytp-offline-slate-open-button"),"click",()=>{g.Zn(this.element,"ytp-offline-slate-collapsed")});
this.hide();A=this.getVideoData();A.getPlayerResponse()&&(A=A.getPlayerResponse().playabilityStatus)&&this.dM(A);A=this.api.getPresentingPlayerType()===8&&!this.getVideoData().KU;var P=this.api.getPresentingPlayerType()===8;g.Cp(this.element,"ytp-offline-slate-premiere-trailer",A);g.Cp(this.element,"ytp-offline-slate-hide-background",P)}getPlayerType(){if(this.api.getPresentingPlayerType()===8)return 1}getVideoData(){return this.api.getVideoData({playerType:this.getPlayerType()})}dM(A){var P=A?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate;
if(P){this.Y=A;P=P.liveStreamOfflineSlateRenderer;P.canShowCountdown?this.L():hR(this,P);var D=A?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer?.thumbnail;if(D){let d=0,u=null;D=D.thumbnails;for(let B=0;B<D.length;B++)D[B].width>d&&(d=D[B].width||0,u=D[B].url);u&&(this.background.style.backgroundImage=`url(${u})`)}else this.background.style.backgroundImage="";P.actionButtons?(this.O||(this.O=new wsJ(this.api),this.O.i8(this.jH("ytp-offline-slate-buttons")),
g.V(this,this.O)),SnA(this.O,P.actionButtons&&P.actionButtons[0])):this.O&&SnA(this.O,null);this.Y=A}else this.Y=null;this.A()}A(A){if(this.api.getPresentingPlayerType()===8)var P=!0;else{var D=this.api.getPlayerStateObject(),d=this.getVideoData();P=d.isLivePlayback&&(D.isBuffering()||D.O(2)||D.O(64));var u=d.autonavState===2&&D.O(2);D=D.isPlaying()&&!g.ct(d)&&!this.api.isAtLiveHead(void 0,!0);P=P&&!D&&!u}P&&this.Y?this.uf?A?.fJ(2)&&!this.getVideoData().KU&&(g.Zn(this.element,"ytp-offline-slate-collapsed"),
this.D.stop(),g.Zn(this.N,"ytp-offline-slate-bar-fade"),this.j.start()):(this.show(),this.D.start(),this.api.publish("offlineslatestatechange"),this.U&&this.api.mY()):this.uf&&(this.hide(),this.api.publish("offlineslatestatechange"))}L(){var A=this.Y?.liveStreamability?.liveStreamabilityRenderer?.offlineSlate?.liveStreamOfflineSlateRenderer;if(A){var P=Math.floor(g.E8()/1E3),D=A.canShowCountdown&&Number(A.scheduledStartTime);!D||D<=P?(hR(this,A),this.countdownTimer.stop()):(hR(this,A,g.n8(D-P)),g.MA(this.countdownTimer))}}Nd(){this.countdownTimer.dispose();
this.countdownTimer=null;super.Nd()}};var $2J=class{constructor(A,P){var D=(0,g.N)();this.trigger=A;this.O=P;this.N=D}Y(A){return this.trigger&&A.trigger?this.trigger===A.trigger&&this.O===A.O:!1}isExpired(){return(0,g.N)()-this.N>6E4}toString(){return`heartbeat:${this.trigger}:${this.O}`}};var lsP=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.H4("heartbeat",class extends g.zy{constructor(A){super(A);this.L=!1;this.A=0;this.j=!1;this.Y=new g.jp(()=>{uJ1(this)},0);
this.O=this.heartbeatParams=null;this.D=!1;this.U=new g.ll(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Hy=new g.D9(void 0);this.attestationResponse=Promise.resolve(void 0);this.Z=Promise.resolve(void 0);this.utcOffsetMinutes=-(new w0).getTimezoneOffset();this.N=new g.R9(this);g.V(this,this.Y);g.V(this,this.N);D2q(this);iVt(this);this.N.V(A,"heartbeatparams",this.q3);this.N.V(A,"presentingplayerstatechange",this.Yi);this.N.V(A,"videoplayerreset",this.OC);this.N.V(A,g.is("heartbeat"),
this.onCueRangeEnter);this.D&&this.O&&gDy(this,void 0,this.O);var P=new g.ut(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),D=new g.ut(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});A.ZR([P,D]);kib(this)}Nd(){pq(this);this.player.kX("heartbeat");super.Nd()}onCueRangeEnter(){this.L=!0;if(this.player.G().experiments.EC().O.tG(g.ib)){let A=VD(this);isNaN(A)||IE(this,A)}else IE(this,2E3)}q3(A){this.heartbeatParams=A;this.player.G().experiments.EC().O.tG(g.ib)?
(A=VD(this),isNaN(A)||IE(this,A)):IE(this,2E3)}Yi(A){if(this.player.getPresentingPlayerType()!==8&&this.O?.status!=="UNPLAYABLE")if(A.state.O(2)||A.state.O(64))pq(this),this.D&&(this.L=!0,IE(this,1E3));else{let P=this.player.G().experiments.EC().O.tG(g.bjK);(A.state.O(1)||A.state.O(8)||P&&A.state.O(4))&&IE(this,VD(this))}}OC(){this.player.getPresentingPlayerType()!==3&&IE(this,VD(this))}getPlayerType(){if(this.player.getPresentingPlayerType()===8)return 1}getVideoData(){return this.player.getVideoData({playerType:this.getPlayerType()})}Sv(A){switch(A){case 4:case 3:return!1}return!0}c9(A,
P,D){A={trigger:A,reason:P};D&&(A.serializedServerContext=D.additionalLoggingData);g.dL("heartbeatActionPlayerTransitioned",A)}m4(A){var P="LICENSE",D=fxx(A);if(D)return D.reason||g.jn[P]||"";if(A=A.match(lsP))if(A=Number(A[1]))P=(P=R7F[A.toString()])?P:"LICENSE";return g.jn[P]||""}vV(){return!!this.offlineSlate&&this.offlineSlate.uf}});})(_yt_player);
