(function(g){var window=this;'use strict';var iSJ=async function(A,P,D){A.Y=g.Xp(P,D)},kP=function(A){A.isActive()||A.start()},HSb=function(A,P){var D=new g.PM;
D.languageCode=A.languageCode;D.languageName=A.languageName;D.name=A.name;D.displayName=A.displayName;D.kind=A.kind;D.isDefault=!1;D.O=A.O;D.isTranslateable=A.isTranslateable;D.vssId=A.vssId;D.url=A.url;D.translationLanguage=P;A.xtags&&(D.xtags=A.xtags);A.captionId&&(D.captionId=A.captionId);return D},lu=function(A,P){return P?A.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},$Qy=function(A){return g.FL(A)||A.B("web_enable_caption_language_preference_stickiness")},gwF=async function(A,P){A=
A+"|"+P;
P=await g.AH();if(!P)throw g.jI("gct");return(await g.y7(P)).get("captions",A)},ktF=function(A,P,D){gwF(A,P).then(d=>{d&&D(d.trackData,new g.PM(d.metadata))})},Ql=function(A){if(!lYx.test(A))throw Error("'"+A+"' is not a valid hex color");
A.length==4&&(A=A.replace(Q$t,"#$1$1$2$2$3$3"));A=A.toLowerCase();A=parseInt(A.slice(1),16);return[A>>16,A>>8&255,A&255]},vwR=function(){var A={},P="suggest_correction"in g.Vw?g.Vw.suggest_correction:"Edit caption";
P=P||"";for(let D in A){let d=()=>String(A[D]);
P=P.replace(new RegExp("\\$\\{"+D+"\\}","gi"),d);P=P.replace(new RegExp("\\$"+D,"gi"),d)}return P},vV=function(){return g.Wp("yt-player-caption-display-settings")},Keb=function(A,P){var D=g.Ib(A.segments,P);
D>=0||D<0&&(-D-1)%2===1||(D=-D-1,D>0&&P-A.segments[D-1]===1&&D<A.segments.length&&A.segments[D]-P===1?(g.kt(A.segments,D),g.kt(A.segments,D-1)):D>0&&P-A.segments[D-1]===1?A.segments[D-1]=P:D<A.segments.length&&A.segments[D]-P===1?A.segments[D]=P:(g.xt(A.segments,D,0,P),g.xt(A.segments,D+1,0,P)))},tLy=function(A){return A.O&&A.O.D?A.O.D+A.player.dO()<A.player.getCurrentTime():!1},yVP=function(A,P){if(A.policy.y6&&A.player.N2()){var D=g.HO(P,A.policy,{});
D.set("pot",A.player.N2());D=D.g_()}else D=g.HO(P,A.policy,{}).g_();var d={format:"RAW",withCredentials:!0};if(A.policy.xi){d.method="POST";let U=P.D;U&&Object.keys(U).length>0?d.postBody=g.TF(U,g.el):d.postBody=(0,g.E$)([120,0])}A.j&&(d.responseType="arraybuffer");var u=++A.Hy,B=(0,g.N)();A.Y=g.SB(D,d,3,100,-1,U=>{U.errorCode==="net.timeout"&&A.player.F9("capnt",{rn:u++})}).then(U=>{if(A.policy.sV&&u%100===1){var c=(0,g.N)();
A.player.F9("caprsp",{rn:u,ms:c-B,kb:(U.xhr.responseText.length/1024).toFixed()})}a:{U=U.xhr;A.Q_();if(A.N){var e=!(A.j?U.response:U.responseText)||U.status>=400;if(c=g.ej8(U)){U=g.HO(A.N,A.policy,{});A.N.ux(U,c);yVP(A,A.N);break a}e?A.player.F9("capfail",{status:U.status}):(g.e7("fcb_r",(0,g.N)(),A.player.getVideoData()?.Z||""),c=A.N.Fr[0],e=c.sC,A.A!=null&&A.U!==e&&(A.j?A.A(U.response,(c.startTime+A.player.dO())*1E3):A.A(U.responseText,(c.startTime+A.player.dO())*1E3),A.U=e))}A.N=null;A.Y=null}}).w0(U=>
{A.N=null;
A.Y=null;A.player.F9("capfail",{rn:u,status:U.xhr?.status})});
A.N=P;Keb(A.D,A.N.Fr[0].sC)},aYy=function(A,P){return P!=null&&P in A.Y.O?A.Y.O[P]:null},R_R=function(A,P,D){var d=[];
for(let u in A.Y.O){if(!A.Y.O.hasOwnProperty(u))continue;let B=A.Y.O[u];if(g.kN(B,D||null)){let U=B.info.captionTrack;U&&U.languageCode===P&&d.push(B)}}return d.length?d[0]:null},wSF=function(A,P){var D=[];
for(let u in A.Y.O){if(!A.Y.O.hasOwnProperty(u))continue;var d=A.Y.O[u];if(g.kN(d,P||null)){let B=d.info.id,U=B,c=`.${B}`,e="",H="";if(d=d.info.captionTrack)B=d.languageCode,U=d.displayName,c=d.vssId,e=d.kind,H=d.id;D.push(new g.PM({id:u,languageCode:B,languageName:U,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:e,captionId:H}))}}return D},xQb=function(A,P,D,d){var u=P/360*16;
P>=A&&(A=640,d>D*1.3&&(A=480),u=D/A*16);return u},h_y=function(A){var P=1+.25*(A.fontSizeIncrement||0);
if(A.offset===0||A.offset===2)P*=.8;return P},GtT=function(A,P){var D="vertical-rl";
A.O.il===1&&(D="vertical-lr");g.NA&&(D=D==="vertical-lr"?"tb-lr":"tb-rl");g.Fs(P,"-o-writing-mode",D);g.Fs(P,"-webkit-writing-mode",D);g.Fs(P,"writing-mode",D);g.Fs(P,"text-orientation","upright");g.mR(P,"ytp-vertical-caption");A.Y.params.JM===3&&(g.Fs(P,"text-orientation",""),g.Fs(P,"transform","rotate(180deg)"))},IYJ=function(A,P){var D={},d=P.background?P.background:A.O.Wn.background;
if(P.backgroundOpacity!=null||P.background){var u=P.backgroundOpacity!=null?P.backgroundOpacity:A.O.Wn.backgroundOpacity;d=Ql(d);D.background="rgba("+d[0]+","+d[1]+","+d[2]+","+u+")";A.y_&&(D["box-decoration-break"]="clone",D["border-radius"]=`${A.gM*.375}px`)}if(P.fontSizeIncrement!=null||P.offset!=null)D["font-size"]=`${A.Md*h_y(P)}px`;d=1;u=P.color||A.O.Wn.color;if(P.color||P.textOpacity!=null)u=Ql(u),d=P.textOpacity==null?A.O.Wn.textOpacity:P.textOpacity,u="rgba("+u[0]+","+u[1]+","+u[2]+","+d+
")",D.color=u,D.fill=u;var B=P.charEdgeStyle;B===0&&(B=void 0);if(B){u=`rgba(34, 34, 34, ${d})`;let e=`rgba(204, 204, 204, ${d})`;P.Cu&&(e=u=P.Cu);let H=A.Md/16/2,k=Math.max(H,1);var U=Math.max(2*H,1),c=Math.max(3*H,1);let l=Math.max(5*H,1);d=[];switch(B){case 4:for(;c<=l;c+=H)d.push(`${U}px ${U}px ${c}px ${u}`);break;case 1:U=window.devicePixelRatio>=2?.5:1;for(B=k;B<=c;B+=U)d.push(`${B}px ${B}px ${u}`);break;case 2:d.push(`${k}px ${k}px ${e}`);d.push(`-${k}px -${k}px ${u}`);break;case 3:for(c=0;c<
5;c++)d.push(`0 0 ${U}px ${u}`)}D["text-shadow"]=d.join(", ")}u="";switch(P.fontFamily){case 1:u='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:u='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:u='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:u='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:u='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';
break;case 7:u=g.la()?'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:u='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}u&&(D["font-family"]=u);u=P.offset;u==null&&(u=A.O.Wn.offset);switch(u){case 0:D["vertical-align"]="sub";break;case 2:D["vertical-align"]="super"}P.fontFamily===7&&(D["font-variant"]="small-caps");P.bold&&(D["font-weight"]="bold");P.italic&&(D["font-style"]="italic");P.underline&&
(D["text-decoration"]="underline");P.mL&&(D.visibility="hidden");P.We===1&&A.D&&(D["text-combine-upright"]="all",D["text-orientation"]="mixed",u=g.EI||g.IW,A.Y.params.JM===3?D.transform=u?"rotate(90deg)":"rotate(180deg)":u&&(D.transform="rotate(-90deg)"));if(P.textEmphasis===1||P.textEmphasis===2||P.textEmphasis===3||P.textEmphasis===4||P.textEmphasis===5)if(g.EI)D["font-weight"]="bold";else switch(D["text-emphasis-style"]="filled circle",D["text-emphasis-color"]="currentcolor",D["webkit-text-emphasis"]=
"filled circle",P.textEmphasis){case 4:case 3:D["text-emphasis-position"]="under left";D["webkit-text-emphasis-position"]="under left";break;case 5:case 2:D["text-emphasis-position"]="over right",D["webkit-text-emphasis-position"]="over right"}return D},pSK=function(A,P){if(A.SH&&P.length===0)return 0;
A=1;for(let D=0;D<P.length;D++){let d=P[D];typeof d.text==="string"&&(A+=d.text.split("\n").length-1,d.append||D===0||A++)}return A},K5=function(A){A=A.split("px");
return A.length>0?(A=Number(A[0]))?A:0:0},MLT=function(A,P,D){A.eH=A.eH||!!D;
var d={};Object.assign(d,A.O.Wn);Object.assign(d,D||P.O);Object.assign(d,A.pJ.Wn);(D=!A.j)&&VLR(A);var u=A.ki&&A.Ce&&g.qT(d,A.Ce)?A.ki:j$y(A,d),B=typeof P.text==="string",U=B?P.text.split("\n"):[P.text];for(let e=0;e<U.length;e++){var c=e>0||!P.append;let H=U[e];c&&!D?(VLR(A),u=j$y(A,d)):c&&D&&(D=!1);H&&(u.appendChild(B?g.eW(H):H),B||H.tagName!=="RUBY"||H.childElementCount!==4||g.EI||!g.zE(H.children[2],"text-emphasis")||(c=A.D?"padding-right":"padding-top",g.zE(H.children[2],"text-emphasis-position")&&
(c=A.D?"padding-left":"padding-bottom"),g.DW?g.Fs(u,c,"1em"):g.Fs(u,c,"0.5em")))}A.Ce=d;A.ki=u;A.L.push(P)},VLR=function(A){if(A.j){var P=A.j;
if(A.y_){var D=A.O.textAlign;D===0?(P=P.firstElementChild)&&g.Fs(P,{"border-bottom-left-radius":"0"}):D===1&&(P=P.lastElementChild)&&g.Fs(P,{"border-bottom-right-radius":"0"})}}A.j=g.cv("SPAN");g.Fs(A.j,{display:"block"});g.mR(A.j,"caption-visual-line");A.N.appendChild(A.j)},j$y=function(A,P){var D=g.cv("SPAN");
g.Fs(D,{display:"inline-block","white-space":"pre-wrap"});g.Fs(D,IYJ(A,P));D.classList.add("ytp-caption-segment");A.j.appendChild(D);A.y_&&A.N.children.length>1&&(A=A.O.textAlign,A===0?D.previousElementSibling||g.Fs(D,{"border-top-left-radius":"0"}):A===1&&g.Fs(D,{"border-top-right-radius":"0"}));D.previousElementSibling&&(g.Fs(D.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Fs(D,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return D},
nw1=function(A,P,D){if(A===255&&P===255||!A&&!P)return{LC:A,
Lw:P,result:0};A=XSx[A];P=XSx[P];if(A&128){var d;if(d=!(P&128))d=P,d=D.QI()&&D.Lw===d;if(d)return{LC:A,Lw:P,result:1}}else if(P&128&&1<=A&&A<=31)return{LC:A,Lw:P,result:2};return{LC:A,Lw:P,result:3}},OSb=function(A,P,D,d){P===255&&D===255||!P&&!D?(++A.N===45&&A.reset(),A.D.Y.clear(),A.j.Y.clear()):(A.N=0,bSK(A.D,P,D,d))},Fey=function(A,P){A.O.sort((D,d)=>{var u=D.time-d.time;
return u===0?D.order-d.order:u});
for(let D of A.O)A.time=D.time,D.type===0?OSb(A,D.NR,D.RC,P):D.type===1&&A.Y&496&&bSK(A.j,D.NR,D.RC,P);A.O.length=0},CXx=function(A,P){switch(A){case 0:return mQK[(P&127)-32];
case 1:return owA[P&15];case 2:return ZST[P&31];case 3:return z_P[P&31]}return 0},tk=function(A,P){if(A.style.type===3){var D=0,d=0,u=A.j.time+0,B="",U="",c=u;
for(var e=1;e<=15;++e){var H=!1;for(var k=d?d:1;k<=32;++k){var l=A.N[e][k];if(l.O!==0){D===0&&(D=e,d=k);H=String.fromCharCode(l.O);var Q=l.timestamp;Q<u&&(u=Q);l.timestamp=c;U&&(B+=U,U="");B+=H;H=!0}if((l.O===0||k===32)&&H){U="\n";break}else if(d&&!H)break}if(D&&!H)break}B&&P.D(D,d,u,c,B)}else for(d=D=0,B=u=A.j.time+0,U=1;U<=15;++U)for(c="",e=1;e<=32;++e)if(k=A.N[U][e],l=k.O,l!==0&&(D===0&&(D=U,d=e),H=String.fromCharCode(l),Q=k.timestamp,Q<=u&&(u=Q),c+=H,k.reset()),e===32||l===0)c&&P.D(D,d,u,B,c),
u=B,c="",d=D=0},yl=function(A){return A.N[A.row][A.Y]},aQ=function(A,P,D){P>=2&&A.Y>1&&(--A.Y,yl(A).O=0);
var d=yl(A);d.timestamp=A.j.time+0;d.O=CXx(P,D);A.Y<32&&A.Y++},EwT=function(A,P,D,d){for(let U=0;U<d;U++)for(let c=0;c<=32;c++){var u=A.N[P+U][c],B=A.N[D+U][c];
u.O=B.O;u.timestamp=B.timestamp}},RQ=function(A,P,D){for(let d=0;d<D;d++)for(let u=0;u<=32;u++)A.N[P+d][u].reset()},wS=function(A){A.row=A.O>0?A.O:1;
A.Y=1;RQ(A,0,15)},rVb=function(A){A.style.set(1);
A.O=A.D;A.O.O=0;A.O.style=A.style;A.N.mode=1<<A.O.D},xP=function(A,P,D){var d=A.Y,u=!1;
switch(A.style.get()){case 4:case 1:case 2:A.style.get()===4&&d.O>0||(tk(d,D),wS(A.Y),wS(A.D),d.row=15,d.O=P,u=!0)}A.style.set(3);A.O=d;A.O.style=A.style;A.N.mode=1<<d.D;u?d.Y=1:d.O!==P&&(d.O>P?(tk(d,D),RQ(d,d.row-d.O,P)):d.row<P&&(P=d.O),d.O=P)},Y7T=function(A){A.style.set(4);
A.O=A.text;A.O.style=A.style;A.N.mode=1<<A.O.D},bSK=function(A,P,D,d){A.Y.update();
P=nw1(P,D,A.Y);switch(P.result){case 0:return;case 1:case 2:return}var u=P.LC;P=P.Lw;if(32<=u||!u)A.O.mode&A.O.Y&&(D=u,D&128&&(D=127),P&128&&(P=127),A=A.D.O,D&96&&aQ(A,0,D),P&96&&aQ(A,0,P),D!==0&&P!==0&&A.style.type===3&&tk(A,d));else if(u&16)a:if(!A.Y.matches(u,P)&&(D=A.Y,D.LC=u,D.Lw=P,D.state=2,D=u&8?A.U:A.N,A.D=D,A.O.mode=1<<(A.j<<2)+(D.j<<1)+(D.style.type===4?1:0),(A.O.mode|1<<(A.j<<2)+(D.j<<1)+(D.style.type!==4?1:0))&A.O.Y))if(P&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(u&7)<<1|P>>5&1];
A=P&16?((P&14)>>1)*4:0;P=D.O;switch(D.style.get()){case 4:d=P.row;break;case 3:if(d!==P.row){if(d<P.O&&(d=P.O,d===P.row))break;var B=1+P.row-P.O;let U=1+d-P.O;EwT(P,U,B,P.O);D=B;u=P.O;U<B?(B=U+u-B,B>0&&(D+=B,u-=B)):(B=B+u-U,B>0&&(u-=B));RQ(P,D,u)}}P.row=d;P.Y=A+1}else switch(u&7){case 1:switch(P&112){case 32:aQ(D.O,0,32);break a;case 48:P===57?(d=D.O,yl(d).O=0,d.Y<32&&d.Y++):aQ(D.O,1,P&15)}break;case 2:P&32&&aQ(D.O,2,P&31);break;case 3:P&32&&aQ(D.O,3,P&31);break;case 4:case 5:if(32<=P&&P<=47)switch(P){case 32:rVb(D);
break;case 33:d=D.O;d.Y>1&&(--d.Y,yl(d).O=0);break;case 36:d=D.O;A=yl(d);for(P=0;P<=15;P++)for(D=0;D<=32;D++)if(d.N[P][D]===A){for(;D<=32;D++)d.N[P][D].reset();break}break;case 37:xP(D,2,d);break;case 38:xP(D,3,d);break;case 39:xP(D,4,d);break;case 40:aQ(D.O,0,32);break;case 41:d=D;d.style.set(2);d.O=d.Y;d.O.O=0;d.O.style=d.style;d.N.mode=1<<d.O.D;break;case 42:d=D;A=d.text;A.O=15;A.style.set(4);wS(A);Y7T(d);break;case 43:Y7T(D);break;case 44:A=D;P=A.Y;switch(A.style.get()){case 1:case 2:case 3:tk(P,
d)}RQ(P,0,15);break;case 45:b:{P=D;A=P.O;switch(P.style.get()){default:case 2:case 1:break b;case 4:if(A.row<15){++A.row;A.Y=1;break b}break;case 3:}A.O<2&&(A.O=2,A.row<A.O&&(A.row=A.O));P=A.row-A.O+1;tk(A,d);EwT(A,P,P+1,A.O-1);RQ(A,A.row,1)}break;case 46:RQ(D.D,0,15);break;case 47:A=D,tk(A.Y,d),A.D.updateTime(A.N.time+0),d=A.D,A.D=A.Y,A.Y=d,rVb(A)}break;case 7:switch(P){case 33:case 34:case 35:d=D.O,(d.Y+=P&3)>32&&(d.Y=32)}}},TQR=function(A,P,D,d,u,B,U){var c=B[0],e=U[c.getAttribute("p")];
if(e.I_===1){var H=B[1],k=B[2];B=B[3];c.getAttribute("t");H.getAttribute("t");k.getAttribute("t");B.getAttribute("t");c.getAttribute("p");H.getAttribute("p");B.getAttribute("p");U=U[k.getAttribute("p")];c=NQJ(c.textContent,H.textContent,k.textContent,B.textContent,U);return new hk(A,P,u,D,c,d,e)}switch(e.I_){case 9:case 10:e.textEmphasis=1;break;case 11:e.textEmphasis=2;break;case 12:e.textEmphasis=3;break;case 13:e.textEmphasis=4;break;case 14:e.textEmphasis=5}return new hk(A,P,u,D,c.textContent||
"",d,e)},NQJ=function(A,P,D,d,u){var B=g.la(),U=B?g.cv("DIV"):g.cv("RUBY"),c=g.cv("SPAN");
c.textContent=A;U.appendChild(c);A=B?g.cv("DIV"):g.cv("RP");A.textContent=P;U.appendChild(A);P=B?g.cv("DIV"):g.cv("RT");P.textContent=D;U.appendChild(P);D=u.I_;if(D===10||D===11||D===12||D===13||D===14)if(g.Fs(P,"text-emphasis-style","filled circle"),g.Fs(P,"text-emphasis-color","currentcolor"),g.Fs(P,"webkit-text-emphasis","filled circle"),u.I_===11||u.I_===13)g.Fs(P,"webkit-text-emphasis-position","under left"),g.Fs(P,"text-emphasis-position","under left");D=!0;if(u.I_===4||u.I_===7||u.I_===12||
u.I_===14)g.Fs(U,"ruby-position","over"),g.Fs(U,"-webkit-ruby-position","before");else if(u.I_===5||u.I_===6||u.I_===11||u.I_===13)g.Fs(U,"ruby-position","under"),g.Fs(U,"-webkit-ruby-position","after"),D=!1;u=B?g.cv("DIV"):g.cv("RP");u.textContent=d;U.appendChild(u);B&&(d=D,g.Fs(U,{display:"inline-block",position:"relative"}),B=U.firstElementChild.nextElementSibling,g.Fs(B,"display","none"),B=B.nextElementSibling,g.Fs(B,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Fs(U.lastElementChild,"display","none"),d?(g.Fs(U,"padding-top","0.6em"),g.Fs(B,"top","0")):(g.Fs(U,"padding-bottom","0.6em"),g.Fs(B,"bottom","0")));return U},S7A=function(A){var P="_"+GX++;
return new IQ(0,0x8000000000000,0,P,A)},p5=function(A,P){A=A.getAttribute(P);
if(A!=null)return Number(A)},Vl=function(A,P){A=A.getAttribute(P);
if(A!=null)return A==="1"},j$=function(A,P){A=p5(A,P);
return A!==void 0?A:null},XQ=function(A,P){A=A.getAttribute(P);
if(A!=null)return MK.test(A),A},JVb=function(A,P){var D={},d=P.getAttribute("ws");
Object.assign(D,d?A.Z[d]:A.D);A=j$(P,"mh");A!=null&&(D.XX=A);A=j$(P,"ju");A!=null&&(D.textAlign=A);A=j$(P,"pd");A!=null&&(D.JM=A);A=j$(P,"sd");A!=null&&(D.il=A);A=XQ(P,"wfc");A!=null&&(D.windowColor=A);P=p5(P,"wfo");P!==void 0&&(D.windowOpacity=P/255);return D},LeF=function(A,P){var D={},d=P.getAttribute("wp");
d&&Object.assign(D,A.A[d]);A=j$(P,"ap");A!=null&&(D.Wz=A);A=p5(P,"cc");A!=null&&(D.gJ=A);A=p5(P,"ah");A!=null&&(D.tq=A);A=p5(P,"rc");A!=null&&(D.tn=A);P=p5(P,"av");P!=null&&(D.gn=P);return D},q7T=function(A,P,D,d){var u={};
Object.assign(u,LeF(A,P));Object.assign(u,JVb(A,P));d?g.qT(u,A.D)?(d=A.j,u=A.D):d="_"+GX++:d=P.getAttribute("id")||"_"+GX++;A=p5(P,"t")+D;P=p5(P,"d")||0x8000000000000;if(u.JM===2||u.JM===3)D=u.tn,u.tn=u.gJ,u.gJ=D;return new IQ(A,P,0,d,u)},n5=function(A){A=g.j5(Math.round(A),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-A.length)+A},s$t=function(A,P,D,d,u){d===0&&(d=0x8000000000000);
var B={};P.wpWinPosId&&Object.assign(B,A.D.get(P.wpWinPosId));P.wsWinStyleId&&Object.assign(B,A.j.get(P.wsWinStyleId));A=P.rcRowCount;A!==void 0&&(B.tn=A);P=P.ccColCount;P!==void 0&&(B.gJ=P);if(B.JM===2||B.JM===3)P=B.tn,B.tn=B.gJ,B.gJ=P;return new IQ(D,d,0,u,B)},bu=function(A){var P=A.byteOffset;
A.byteOffset+=1;return A.O.getUint8(P)},OH=function(A){var P=A.byteOffset;
A.byteOffset+=4;return A.O.getUint32(P)},A4y=function(A){if(typeof A==="string")return!1;
A=new Wet(A,0);return fYx(A)},fYx=function(A){if(!(A.byteOffset<A.O.byteLength)||OH(A)!==1380139777)return!1;
A.version=bu(A);if(A.version>1)return!1;bu(A);bu(A);bu(A);return!0},PQ1=function(A,P){if(!P)return"";
A.D&&A.Y.params.il!==1&&(P*=-1);return`translate${A.D?"X":"Y"}(${P}px)`},DRq=function(A){A.b8=Array.from(A.element.getElementsByClassName("caption-visual-line"));
for(var P=A.Y.params.tn,D=0,d=0,u=A.b8.length-1;D<P&&u>-1;){var B=A.b8[u];d+=A.D?B.offsetWidth:B.offsetHeight;D++;u--}A.OC=d;P=Math;D=P.max;isNaN(A.xi)&&((d=A.O.gJ)?(u=g.cv("SPAN"),g.lA(u,"\u2013".repeat(d)),g.Fs(u,IYJ(A,A.O.Wn)),A.N.appendChild(u),A.xi=u.offsetWidth,A.N.removeChild(u)):A.xi=0);d=A.N;A.Hy=D.call(P,A.xi,A.gO,(A.D?d.offsetHeight:d.offsetWidth)+1)},dRA=function(A,P){DRq(A);
var D=A.b8.reduce((d,u)=>(A.D?u.offsetWidth:u.offsetHeight)+d,0);
D=A.OC-D;if(D!==A.UC){let d=D>0&&A.UC===0,u=D<A.UC;P||isNaN(D)||d||!u||(g.mR(A.element,"ytp-rollup-mode"),A.V(A.element,"transitionend",A.I2));g.Fs(A.N,"transform",PQ1(A,D));A.UC=D}DRq(A)},BZx=function(A,P,D,d){var {formatId:u,
sC:B,startTimeMs:U,durationMs:c}=A.uw(P),e={formatId:u,startTimeMs:U,durationMs:c,cJ:B,o_:B},H=u5P(A.rI,e.startTimeMs),k=H>=0?A.rI[H]:null,l=k?k.startTimeMs+k.durationMs:0,Q=e.startTimeMs+e.durationMs;!k||e.startTimeMs-l>A.D?A.rI.splice(H+1,0,e):(k.durationMs=Math.max(l,Q)-k.startTimeMs,k.o_=Math.max(k.o_,e.o_));d(A.rI);d=g.KC(P);A=A.j;d=d.buffer.slice(d.byteOffset,d.byteLength+d.byteOffset);P=P.info.N;A.Hy?A.A==null?g.vc(A.logger,350058965,"Null loaded track meta data at captions data received"):
D.oD(d,A.A,P*1E3):g.vc(A.logger,350058965,"Null Representation at captions data received")},eot=function(A,P){A.Y=(D,d)=>{if(A.K.G().experiments.o2("html5_sabr_live_support_subfragmented_captions"))(A.O?A.O=A.O.j(D):(A.O=D,URq(A.O)),A.O)?D.info.Pn&&(c4F(A.O),BZx(A,A.O,P,d),A.O=null):g.vc(A.logger,350058965,"Empty slice");
else if(D.info.Pn){var u=D;if(A.ix.length>0){for(u=A.ix.shift();A.ix.length>0;)u=u.j(A.ix.shift());u=u.j(D)}u?(URq(u),c4F(u),BZx(A,u,P,d)):g.vc(A.logger,350058965,"Empty slice")}else A.ix.push(D)};
A.K.addEventListener("sabrCaptionsDataLoaded",A.Y)},u5P=function(A,P){A=g.Ib(A,{startTimeMs:P},(D,d)=>D.startTimeMs-d.startTimeMs);
return A>=0?A:-A-2},URq=function(A){try{var P=g.ae(A)*1E3}catch(D){P=A.info.startTime*1E3}P<0&&(P=A.info.startTime*1E3);
A.info.startTime=P/1E3;A.info.N=P/1E3},c4F=function(A){try{var P=g.APQ(A)*1E3}catch(D){P=A.info.duration*1E3}P<0&&(P=A.info.duration*1E3);
A.info.duration=P/1E3;A.info.L=P/1E3},ivt=function(A,P){if(!g.jxB(A)||A.O!=null&&g.go(P,A.O)&&A.O.O.rawcc!=null)return!1;
P=!!A.O&&A.O.isManifestless&&Object.values(A.O.O).some(D=>g.kN(D,"386"));
A=!!A.O&&!A.O.isManifestless&&g.Ve8(A.O);return P||A},Hvt=function(A,P,D){var d=[];
for(let u in A.Y.O){if(!A.Y.O.hasOwnProperty(u))continue;let B=A.Y.O[u];if(g.kN(B,D||null)){let U=B.info.captionTrack;U&&U.languageCode===P&&d.push(B)}}return d.length?d[0]:null},$RJ=function(A,P){var D=[];
for(let u in A.Y.O){if(!A.Y.O.hasOwnProperty(u))continue;var d=A.Y.O[u];if(g.kN(d,P||null)){let B=d.info.id,U=B,c=`.${B}`,e="",H="";if(d=d.info.captionTrack)B=d.languageCode,U=d.displayName,c=d.vssId,e=d.kind,H=d.id;D.push(new g.PM({id:u,languageCode:B,languageName:U,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:e,captionId:H}))}}return D},k5q=function(A){var P=g2A.length;
if(A.byteLength<P)return!1;A=new Uint8Array(A,0,P);for(let D=0;D<P;D++)if(g2A[D]!==A[D])return!1;return!0},FQ=function(A){A=A.split(":");
var P=0;for(let D of A)P=P*60+Number(D);return P*1E3},lZJ=function(A,P,D,d){d=Object.assign({XX:0},d);
return new IQ(A,P,D,"_"+GX++,d)},Q3t=function(A,P,D,d,u,B,U,c,e){switch(U.tagName){case "b":c.bold=!0;
break;case "i":c.italic=!0;break;case "u":c.underline=!0}for(let k=0;k<U.childNodes.length;k++){var H=U.childNodes[k];if(H.nodeType===3)H=new hk(P,D,d,u.id,H.nodeValue,B||k>0,g.SF(c)?void 0:c),e.push(H),u.O.push(H);else{let l={};Object.assign(l,c);Q3t(A,P,D,d,u,!0,H,l,e)}}},Kcx=function(A,P,D){if(typeof P==="string"||A4y(P))return[{trackData:P,
yA:D}];if(typeof P==="string"&&P.substring(0,6)==="WEBVTT"||typeof P!=="string"&&k5q(P))return[{trackData:P,yA:D}];var d=new DataView(P);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var u=g.iA8(d);if(A.JX&&u){var B=g.ABb(u),U=g.PPD(u);u=u.segmentNumber;B&&u&&A.JX.Oq(u,B,U)}A=g.xU(d,1835295092);if(!A||!A.length||!A[0].size)return[];B=[];for(U=0;U<A.length;U++)u=A[U],u=new Uint8Array(P,u.dataOffset,u.size-(u.dataOffset-u.offset)),u=g.V_(u),B.push({trackData:u,yA:D+U*1E3});v2b(d,B,D);return B=
B.filter(c=>!!c.trackData)},y4t=function(A,P,D){A.O||(A.O=new t9x);
A=A.O.N(P,D);Math.random()<.01&&g.ia(Error("Deprecated subtitles format in web player: WebVTT"));return A},v2b=function(A,P,D){var d=g.tp(A,0,1836476516),u=9E4;
d&&(u=g.y1(d)||9E4);d=0;var B=g.xU(A,1836019558);for(let c=0;c<B.length;c++){var U=B[c];c<P.length&&(U=g.tp(A,U.dataOffset,1953653094))&&(U=g.tp(A,U.dataOffset,1952867444))&&(U=g.wT(U)/u*1E3,c===0&&(d=U),P[c].yA=U-d+D||D*c*1E3)}},aZy=function(A){var P={};
if(A=g.r7(A))P.lang=A,g.WqF.test(A)&&(P.JM=1);return P},mi=function(A){return A.N==="HLS"&&A.Ru?!0:A.ki&&A.Ru&&A.N!=="LIVE"&&A.N!=="SABR_LIVE"},RoK=function(A){return!A.D&&A.ki&&A.SH&&(A.N==="LIVE"||A.N==="SABR_LIVE")},oQ=function(A,P,D=!1){var d=A.X.B("enable_player_captions_new_style_defaults")?w$T:xRK,u=d.Wn;
A.j={};Object.assign(A.j,d);A.j.Wn={};Object.assign(A.j.Wn,u);A.U={Wn:{}};var B=P.backgroundOverride?A.U:A.j,U=P.background||u.background;MK.test(U);B.Wn.background=U;B=P.colorOverride?A.U:A.j;U=P.color||u.color;MK.test(U);B.Wn.color=U;B=P.windowColorOverride?A.U:A.j;U=P.windowColor||d.windowColor;MK.test(U);B.windowColor=U;B=P.backgroundOpacityOverride?A.U:A.j;U=P.backgroundOpacity;U==null&&(U=u.backgroundOpacity);B.Wn.backgroundOpacity=U;B=P.fontSizeIncrementOverride?A.U:A.j;U=P.fontSizeIncrement;
U==null&&(U=u.fontSizeIncrement);B.Wn.fontSizeIncrement=U;U=P.fontStyleOverride?A.U:A.j;B=P.fontStyle;B==null&&(B=u.bold&&u.italic?3:u.bold?1:u.italic?2:0);U=U.Wn;switch(B){case 1:U.bold=!0;delete U.italic;break;case 2:delete U.bold;U.italic=!0;break;case 3:U.bold=!0;U.italic=!0;break;default:delete U.bold,delete U.italic}B=P.textOpacityOverride?A.U:A.j;U=P.textOpacity;U==null&&(U=u.textOpacity);B.Wn.textOpacity=U;B=P.windowOpacityOverride?A.U:A.j;U=P.windowOpacity;U==null&&(U=d.windowOpacity);B.windowOpacity=
U;d=P.charEdgeStyleOverride?A.U:A.j;B=P.charEdgeStyle;B==null&&(B=u.charEdgeStyle);d.Wn.charEdgeStyle=B;d=P.fontFamilyOverride?A.U:A.j;B=P.fontFamily;B==null&&(B=u.fontFamily);d.Wn.fontFamily=B;A.loaded&&A.OH();D&&g.sf("yt-player-caption-display-settings",P,2592E3)},Z0=function(A,P,D){P&&!A.Yi?(P=S7A({JM:0,
lang:"en"}),A.Yi=[P,new hk(P.start,P.end-P.start,0,P.id,D??"Captions look like this")],A.player.ZR(A.Yi)):!P&&A.Yi&&(hoT(A,A.Yi),A.Yi=null)},IZT=function(A){if(A.X.B("enable_player_captions_persistence_state_machine")){var P=g.Wp("yt-player-caption-persistence");
if(P==null){let D=g.eP().tG(65);if(D===!0)P=!1;else{let d=g.FL(A.X)?zX(A):G5x(A);d!=null?P=!!d:D===!1&&(P=!0)}P!==void 0&&C5(A,P)}return P}},zX=function(A){if(!A.K.isInline())return g.Wp("yt-player-sticky-caption")},G5x=function(A){if(!A.storage)return null;
try{var P=A.storage.get("module-enabled")}catch(D){A.storage.remove("module-enabled")}return P},EH=function(A){if(A.X.B("enable_player_captions_persistence_state_machine"))return IZT(A);
var P=void 0,D=g.eP().tG(65);if(g.FL(A.X)&&D!=null){if(zX(A)!=null)return!1;P=!D}return P},p$F=function(A){if(A.X.Cp===1||A.videoData.Q6===1||g.UK(A.videoData,"yt:cc")==="alwayson")return!0;
if(A.videoData.captionTracks.length)var P=A.getAudioTrack().Y;if(A.X.B("enable_player_captions_persistence_state_machine")){var D=IZT(A);if(D!==void 0)return!!D}else if(A.X.Cp===2&&(g.FL(A.X)?D=zX(A):D=G5x(A),D!=null))return!!D;D=lu(A.player.getAudioTrack(),g.FL(A.X));var d=g.UK(A.videoData,"yt:cc");if(EH(A)===void 0){if(D==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(D==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return P==="ON"||g.UK(A.videoData,
"yt:cc")==="on"},rS=function(A,P=!1){if(A.Y&&!P||!A.videoData.captionTracks.length)return!1;
A=A.getAudioTrack();return!!A.O||A.Y==="FORCED_ON"},V9J=function(A,P){if(A.Y){var D=A.K.gI().cD().textTracks,d=null;
A.N==="HLS"?d=A.Y.getId():d=A.Y.toString();for(let B=0;B<D.length;B++){var u=D[B];u.id===d&&(P?u.mode!=="showing"&&(u.mode="showing",u=A.Y,A.jY(u,!!u,YP(A)?"g":A.L?"m":"s")):u.mode==="showing"&&(u.mode="disabled"))}}},YP=function(A){var P=NK(A);
return!!P&&A.Y===P},j31=function(A,P){if(A.N==="HLS")return!1;
g.lk(A.videoData)&&(P=!0);P||(P=A.N==="TTS"?!1:A.N==="INNERTUBE"?!1:!0);return P||A.X.B("web_watch_disable_account_level_captions_settings")&&g.FL(A.X)?!0:!!g.eP().tG(66)},NK=function(A){return A.Z&&A.Z.O},TX=function(A,P){if(!A.O)return null;
if(A.Z&&A.Z.D)return A.Z.D;P=j31(A,P);P=g.Yz(A.O.O,P);var D=null;if($Qy(A.X)){var d=A.K.isInline()?void 0:g.Wp("yt-player-caption-sticky-language");var u=[d,A.videoData.captionsLanguagePreference,A.X.captionsLanguagePreference,g.UK(A.videoData,"yt:cc_default_lang")];let c=!1;for(let e=0;e<u.length;e++){let H=u[e];if(H){c=!0;for(var B=0;B<P.length;B++)if(g.r7(P[B])===H)return P[B];for(B=0;B<P.length;B++)if(g.r7(P[B]).split("-")[0]===H.split("-")[0])return P[B]}}if(c&&A.O&&(u=A.O.Z,u.length))for(var U of u)if(U.languageCode===
d){D=U;break}}else for(U=[A.videoData.captionsLanguagePreference,A.X.captionsLanguagePreference,g.UK(A.videoData,"yt:cc_default_lang")],d=0;d<U.length;d++)for(u=0;u<P.length;u++)if(g.r7(P[u])===U[d])return P[u];U=null;A.Z&&A.Z.N&&(U=A.Z.N);U||(U=P.find(c=>c.isDefault)||null);
U||(U=P[0]||NK(A));U&&D&&g.r7(U).split("-")[0]!==D.languageCode.split("-")[0]&&(U=HSb(U,D));return U},qK=function(A,P,D){A.loaded&&A.unload();
D!=null&&(A.L=D,A.L&&(A.X.B("enable_player_captions_persistence_state_machine")?C5(A,!!P):g.FL(A.X)?S$(A,!!P):Jk(A,!!P)));P!==null||rS(A,!0)||A.jY(P,!!P,A.L?"m":"s");A.Y=P;rS(A)&&(A.Y=NK(A));L5(A,A.Y??void 0);A.load()},C5=function(A,P){A.X.B("enable_player_captions_persistence_state_machine")&&g.sf("yt-player-caption-persistence",P,3122064E3)},S$=function(A,P){A.K.isInline()||g.sf("yt-player-sticky-caption",P,2592E3)},Jk=function(A,P){if(A.storage)try{A.storage.set("module-enabled",P)}catch(D){}},
L5=function(A,P){A.X.B("html5_modify_caption_vss_logging")&&(A.videoData.eB=P)},X$t=function(A,P){var D=A.hG[P.id];
D&&D.Y!==P&&(D.dispose(),delete A.hG[P.id],D=null);D||(D=M9T(A,P))&&(A.hG[P.id]=D)},n2b=function(A,P){var D=P.windowId;
A.y_[D]||(A.y_[D]=[]);A.y_[D].push(P)},M9T=function(A,P){var D=bvA(A);
if(!D)return null;var d=A.Y?g.r7(A.Y):null;d&&g.WqF.test(d)&&(P.params.JM=1);var u=A.I2.getPlayerSize();d=u.height*A.Hy.height;u=u.width*A.Hy.width;A.X.playerStyle!=="google-live"||A.j.isDefault||Object.assign(P.params,A.j);switch(P.params.XX!=null?P.params.XX:P.O.length>1?1:0){case 1:return new OvA(P,A.j,A.U,D.width,D.height,u,d,A.X.experiments,A.gM.bind(A),A.K);case 2:return new FcT(P,A.j,A.U,D.width,D.height,u,d,A.X.experiments,A.gM.bind(A),A.K);default:return new sH(P,A.j,A.U,D.width,D.height,
u,d,A.X.experiments,A.gM.bind(A),A.K)}},bvA=function(A){var P=A.I2.getVideoContentRect(!0).height,D=A.I2.getVideoContentRect(!0).width;
if(!P||!D)return null;P*=A.Hy.height;D*=A.Hy.width;return{width:D,height:P}},hoT=function(A,P){A.player.mh(P);
for(let D of P)g.ly(A.xi,D);kP(A.eH)},mR1=function(A,P){if(!A.O)return{};
if(P){g.SF(P)||A.tW(P.vss_id,"m");if(A.D&&A.N!=="HLS"||!g.O8(P))return;if(g.SF(P)){qK(A,null,!0);return}let d;var D=g.Yz(A.O.O,!0);for(let u=0;u<D.length;u++){let B=D[u];B.languageCode!==P.languageCode||d&&(B.languageName!==P.languageName||(B.captionId||"")!==(P.captionId||"")||g.CH(B)!==P.displayName)||(d=P.translationLanguage?HSb(B,P.translationLanguage):B)}A.W_(P.position);!d||d===A.Y&&A.loaded||(P=g.FZ(),D=g.r7(d),P.length&&D===P[P.length-1]||(P.push(D),g.sf("yt-player-caption-language-preferences",
P)),$Qy(A.X)&&!A.K.isInline()&&g.sf("yt-player-caption-sticky-language",D,2592E3),qK(A,d,!0))}else return A.loaded&&A.Y&&!YP(A)?g.EG(A.Y):{};return""};
g.AL.prototype.Oq=g.Q9(68,function(A,P,D){this.Y.set(A,{WL:P,Ff:D})});
g.Ph.prototype.Oq=g.Q9(67,function(A,P,D){this.Hy.Oq(A,P,D)});
g.Cl.prototype.OC=g.Q9(66,function(){return!1});
g.Cl.prototype.D=g.Q9(65,function(){});
g.Ea.prototype.D=g.Q9(64,function(A,P,D){this.Q_();P=this.U(A,P);var d=this.JG.G().B("html5_report_captions_ctmp_qoe"),u=(0,g.N)();this.N();iSJ(this,P,{format:"RAW",onSuccess:B=>{this.Y=null;if(d){var U=(B.responseText.length/1024).toFixed();let c=(0,g.N)();this.videoData.F9("capresp",{ms:c-u,kb:U})}U=B.getResponseHeader&&B.getResponseHeader("Content-Length")?Number(B.getResponseHeader("Content-Length")):0;D.oD(B.responseText,A,void 0,void 0,U)},
onError:d?B=>{this.videoData.F9("capfail",{status:B?.status??0})}:void 0,
withCredentials:!0})});
g.rO.prototype.D=g.Q9(63,function(A,P,D){this.Q_();P=this.U(A,P);this.N();this.Y=g.Xp(P,{format:"RAW",onSuccess:d=>{this.Y=null;var u=d.getResponseHeader&&d.getResponseHeader("Content-Length")?Number(d.getResponseHeader("Content-Length")):0;D.oD(d.responseText,A,void 0,void 0,u)},
withCredentials:!0})});
g.IR.prototype.L=g.Q9(62,function(){this.mediaElement.L()});
g.wX.prototype.L=g.Q9(61,function(){var A=g.Lu(document,"track",void 0,this.O);for(let P=0;P<A.length;P++)g.gE(A[P])});
g.IR.prototype.eH=g.Q9(60,function(){return this.mediaElement.eH()});
g.wX.prototype.eH=g.Q9(59,function(){return!(!this.O.textTracks||!this.O.textTracks.addEventListener)});
g.IR.prototype.xi=g.Q9(58,function(){return this.mediaElement.xi()});
g.wX.prototype.xi=g.Q9(57,function(){return!!this.O.textTracks});
g.IR.prototype.Yi=g.Q9(56,function(A){this.mediaElement.Yi(A)});
g.wX.prototype.Yi=g.Q9(55,function(A){for(let P=0;P<A.length;P++)this.O.appendChild(A[P])});
g.Kl.prototype.tW=g.Q9(42,function(A,P){this.app.wM().tW(A,P)});
g.YG.prototype.tW=g.Q9(41,function(A,P){this.l8.tW(A,P)});
g.nl.prototype.tW=g.Q9(40,function(A,P){A=[A,P];g.KR(this,g.ah(this.provider),"cfi",A)});
g.Oa.prototype.tW=g.Q9(39,function(A,P){this.qoe&&this.qoe.tW(A,P)});
g.sU.prototype.tW=g.Q9(38,function(A,P){this.GI.tW(A,P)});
g.qi.prototype.tW=g.Q9(37,function(){});
g.Kl.prototype.jY=g.Q9(36,function(A,P,D){this.app.wM().jY(A,P,D)});
g.YG.prototype.jY=g.Q9(35,function(A,P,D){this.l8.jY(A,P,D)});
g.nl.prototype.jY=g.Q9(34,function(A,P,D){if(this.ki!==A||this.Ns!==P)P=P==="rawcc"?"":P,D=[A,P,this.ki,D],g.KR(this,g.ah(this.provider),"cfs",D),this.ki=A,this.Ns=P});
g.Oa.prototype.jY=g.Q9(33,function(A,P,D){this.qoe&&this.qoe.jY(A,P,D)});
g.sU.prototype.jY=g.Q9(32,function(A,P,D){this.GI.jY(A,P,D)});
g.qi.prototype.jY=g.Q9(31,function(){});
g.Ua.prototype.tC=g.Q9(10,function(A){return(A=this.N(A))?A.O:0});
g.ev.prototype.tC=g.Q9(9,function(){return 0});
g.PM.prototype.Y=g.Q9(8,function(){return this.vssId});
var Q$t=/#(.)(.)(.)/,lYx=/^#(?:[0-9a-f]{3}){1,2}$/i,o2A={en:"English"},Zvx=class extends g.Cl{constructor(A){super(A);this.Y=new Set}j(A){var P=this.JG.gI();if(P&&P.cD()){P=P.cD().textTracks;for(let D of P)D.kind==="subtitles"&&!this.Y.has(D.language)&&D.language&&(g.$N(this.O,new g.PM({languageCode:D.language,languageName:D.language,kind:D.kind,id:D.id,displayName:o2A[D.label]||D.label,vss_id:`.${D.language}`})),this.Y.add(D.language))}g.Yz(this.O).length>0&&A.Bk()}},zoF=class{constructor(){this.segments=
[]}contains(A){A=g.Ib(this.segments,A);return A>=0||A<0&&(-A-1)%2===1}length(){return this.segments.length/2}},CQb=class extends g.a3{constructor(A,P,D,d,u,B){super();this.policy=A;this.player=P;this.TN=D;this.A=d;this.j=u;this.OC=B;this.D=new zoF;this.U=-1;this.Y=this.N=this.O=null;this.Hy=0;this.L=new g.jp(this.Yi,1E3,this);this.events=new g.R9(this);g.V(this,this.L);g.V(this,this.events);this.events.V(P,"SEEK_COMPLETE",this.Z);this.Z();this.Yi()}Nd(){super.Nd();this.Y&&this.Y.cancel()}Z(){this.seekTo(this.player.getCurrentTime())}seekTo(A){A-=
this.player.dO();var P=this.O;this.O=g.s8(this.TN.U(A).Fr);P!==this.O&&this.OC&&this.OC()}reset(){this.D=new zoF;this.U=-1;this.Y&&(this.Y.cancel(),this.Y=null)}Yi(){this.Q_();var A;if(A=this.O!=null)A=this.O,A=A.TN.D(A);if(A&&!this.Y&&!(this.O&&this.O.startTime-this.player.getCurrentTime()>30)){A=this.O;A=A.TN.eH(A);let u=A.Fr[0];if(this.player.getVideoData()?.enableServerStitchedDai){var P=this.player.n8();if(P){var D=u.TN.info.id;let B=u.sC;var d=A.Fr[0].N;if(this.policy.xi){if(P=g.qtb(P,d,B,D,
3))A.D=P}else if(D=P.CO(d,B,D,3))if(d=2,P.zh.has(B)?d=0:g.LG(P,B)&&(d=1),P=d,P===0)D&&(A.O=new g.I5(D));else if(P===2){this.L.start();tLy(this)&&this.seekTo(this.player.getCurrentTime());return}}}u.TN.index.DF(u.sC)?(this.D.contains(A.Fr[0].sC)||yVP(this,A),this.O=g.s8(A.Fr)):tLy(this)&&this.seekTo(this.player.getCurrentTime())}this.L.start()}},E2F=class extends g.Cl{constructor(A,P){super(P);this.Y=A;this.K=P;this.A=null;this.Yi=!1;this.logger=new g.Qk("caps");this.Hy=g.go(this.K,this.Y)}D(A,P,D){this.N();
P=aYy(this,A.getId());P||(P=A.languageCode,P=this.Y.isManifestless?R_R(this,P,"386"):R_R(this,P));if(P){var d=(P.index.tC(P.index.hn())-P.index.getStartTime(P.index.hn()))*1E3,u=new g.aoM(this.K.G());this.A=new CQb(u,this.K,P,(B,U)=>{D.oD(B,A,U,d)},this.Hy||g.I0(P.info),()=>{this.A&&this.A.reset();
this.Yi=!0})}}OC(){var A=this.Yi;
this.Yi=!1;return A}j(A){var P=this.K.G().B("html5_fallback_if_rawcc_missing");var D=this.Y.O.rawcc!=null;if(!this.Hy||!D&&P)P=this.Y.isManifestless?wSF(this,"386"):wSF(this);else{if(!D){g.vc(this.logger,386248249,"rawcc used but unavailable");return}P=[new g.PM({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.PM({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}for(let d of P)g.$N(this.O,
d);A.Bk()}N(){this.A&&(this.A.dispose(),this.A=null)}U(){return""}},MK=/^#(?:[0-9a-f]{3}){1,2}$/i;var r4t=["left","right","center","justify"];var hk=class extends g.ut{constructor(A,P,D,d,u,B=!1,U=null){super(A,A+P,{priority:D,namespace:"captions"});this.windowId=d;this.text=u;this.append=B;this.O=U}toString(){return super.toString()}};var sH=class extends g.W{constructor(A,P,D,d,u,B,U,c,e,H){var k=H.isInline()&&!0,l={};Object.assign(l,P);Object.assign(l,A.params);Object.assign(l,D);var Q={};Object.assign(Q,P.Wn);A.params.Wn&&Object.assign(Q,A.params.Wn);Object.assign(Q,D.Wn);k&&(l.windowOpacity=.6,Q.backgroundOpacity=0);l.Wn=Q;var v=l.JM===1,R=[{C:"span",J:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],p=c.o2("caption_edit_on_hover")&&H.getVideoData().getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;
p&&R.unshift({C:"button",J:"caption-edit",W:{tabindex:"0","aria-label":vwR()},S:[{C:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},S:[{C:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});super({C:"div",J:"caption-window",W:{id:`caption-window-${A.id}`,dir:v?"rtl":"ltr",tabindex:"0",lang:l.lang},S:R});this.experiments=
c;this.L=[];this.eH=!1;this.Y=A;this.Ce=this.ki=null;this.F5=B;this.wI=U;this.j=null;this.maxWidth=B*.96;this.maxHeight=U*.96;this.O=l;this.pJ=D;this.hG=P;this.N=this.jH("captions-text");A=this.N.style;this.y_=c.o2("enable_player_captions_new_style_defaults")&&("boxDecorationBreak"in A||"WebkitBoxDecorationBreak"in A);this.Md=xQb(d,u,B,U);this.eK=e;p&&(this.U=this.jH("caption-edit"),this.V(this.U,"click",()=>{this.eK()}));
this.type=0;this.gM=this.Md*h_y(Q);this.jZ=k;this.SH=c.o2("enable_centered_caption_for_tvfilm_video")&&H.getVideoData().isTvfilmVideo;this.Z=H.G().EC().O.tG(g.mGJ);d=new g.JK(this.element,!0);g.V(this,d);d.subscribe("dragstart",this.Mj,this);d.subscribe("dragmove",this.yv,this);d.subscribe("dragend",this.sB,this);this.OH=this.ZL=this.Ru=this.Ns=0;d="";this.O.windowOpacity&&(d=Ql(this.O.windowColor),d="rgba("+d[0]+","+d[1]+","+d[2]+","+this.O.windowOpacity+")");u={"background-color":d,display:this.O.isVisible===
!1?"none":"","text-align":r4t[this.O.textAlign]};this.y_&&(u["border-radius"]=d?`${this.gM*.375}px`:"");(this.D=this.Y.params.JM===2||this.Y.params.JM===3)&&GtT(this,this.element);g.Fs(this.element,u);k&&this.element.parentElement?.style.setProperty("--caption-window-color",d);switch(this.O.Wz){case 0:case 1:case 2:g.mR(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.mR(this.element,"ytp-caption-window-bottom")}}Mj(A,P){this.ZL=A;this.OH=P;var D=g.qW(this.element,this.element.parentElement);
this.Ns=A-D.x;this.Ru=P-D.y}yv(A,P){if(A!==this.ZL||P!==this.OH){g.FH(this.element,"ytp-dragging")||g.mR(this.element,"ytp-dragging");var D=g.Wv(this.element);A=A-this.Ns-.02*this.F5;var d=P-this.Ru-.02*this.wI,u=(A+D.width/2)/this.maxWidth*3;u=Math.floor(g.j5(u,0,2));var B=(d+D.height/2)/this.maxHeight*3;B=Math.floor(g.j5(B,0,2));P=u+B*3;A=(A+u/2*D.width)/this.maxWidth;A=g.j5(A,0,1)*100;D=(d+B/2*D.height)/this.maxHeight;D=g.j5(D,0,1)*100;this.Y.params.Wz=P;this.Y.params.gn=D;this.Y.params.tq=A;this.Y.params.isDefault=
!1;this.O.Wz=P;this.O.gn=D;this.O.tq=A;this.O.isDefault=!1;this.hG.Wz=P;this.hG.gn=D;this.hG.tq=A;this.hG.isDefault=!1;this.yq()}}sB(){g.Zn(this.element,"ytp-dragging")}yq(){this.A(this.L)}A(A){var P=this.jZ?0:Math.min(this.K$(),this.maxWidth),D=this.Vq(),d=this.jZ;if(d){var u=getComputedStyle(this.N.parentNode);u=K5(u.borderLeftWidth)+K5(u.borderRightWidth)+K5(u.paddingLeft)+K5(u.paddingRight)}else u=0;var B=u;u="";this.Y.params.JM===3&&(u="rotate(180deg)");var U=d?`calc(96% - ${B}px)`:"96%";g.Fs(this.element,
{top:0,left:0,right:"",bottom:"",width:P?`${P}px`:"",height:D?`${D}px`:"","max-width":U,"max-height":U,margin:"",transform:""});this.Le(A);u={transform:u,top:"",left:"",width:P?`${P}px`:"",height:D?`${D}px`:"","max-width":"","max-height":""};U=this.O.Wz;var c=this.O.tq,e=this.O.gn;this.SH&&U!=null&&(c=50,U=Math.floor(U/3)*3+1);c=c*.96+2;switch(U){case 0:case 3:case 6:(d=this.O.Wn.fontSizeIncrement)&&d>0&&this.O.JM!==2&&this.O.JM!==3&&(c=Math.max(c/(1+d*2),2));u.left=`${c}%`;break;case 1:case 4:case 7:u.left=
`${c}%`;c=0;this.Z||(c=this.N.offsetWidth);P||c?(P=P||c+1,u.width=`${P}px`,u["margin-left"]=d?`${P/-2-B/2}px`:`${P/-2}px`):(this.Z&&(u.width="max-content"),u.transform+=" translateX(-50%)");break;case 2:case 5:case 8:u.right=`${100-c}%`}d=e*.96+2;switch(U){case 0:case 1:case 2:u.top=`${d}%`;break;case 3:case 4:case 5:u.top=`${d}%`;d=0;this.Z||(d=this.element.clientHeight);(D=D||d)?(u.height=`${D}px`,u["margin-top"]=`${D/-2}px`):u.transform+=" translateY(-50%)";break;case 6:case 7:case 8:u.bottom=
`${100-d}%`}g.Fs(this.element,u);this.U&&(this.Z?D=this.gM:(A=pSK(this,A),D=this.SH?A>0?this.N.offsetHeight/A:0:this.N.offsetHeight/A),this.U.style.height=`${D}px`,this.U.style.width=`${D}px`,this.element.style.paddingLeft=`${D+5}px`,this.element.style.paddingRight=`${D+5}px`,this.Z||(A=Number(this.element.style.marginLeft.replace("px",""))-D-5,D=Number(this.element.style.marginRight.replace("px",""))-D-5,this.element.style.marginLeft=`${A}px`,this.element.style.marginRight=`${D}px`))}Le(A){if(this.type===
0&&this.Y.params.tn!==void 0&&this.experiments.o2("web_enable_popon_asr_captions")){var P=A,D=this.Y.params.tn;if(P.length===0||D<=0)A=[];else{A=[];for(let u=P.length-1;u>=0;u--){var d=P[u];A.unshift(d);let B=pSK(this,A);if(B>D){A.shift();typeof d.text==="string"&&(P=d.text.split("\n"),D=B-D,P.length-D>0&&(d=new hk(d.start,d.end-d.start,d.priority||0,d.windowId,P.slice(D).join("\n"),d.append,d.O),A.unshift(d)));break}}}}for(d=0;d<A.length&&A[d]===this.L[d];d++);if(this.eH||this.L.length>d)d=0,this.eH=
!1,this.L=[],this.j=this.Ce=this.ki=null,g.Hv(this.N);for(;d<A.length;d++)MLT(this,A[d])}K$(){return 0}Vq(){return 0}toString(){return super.toString()}};var NZJ=class{constructor(){this.N=this.time=this.mode=this.Y=0;this.D=new YTF(this);this.j=new YTF(this);this.O=[];this.clear()}clear(){this.N=this.time=this.mode=0;this.O=[];this.reset()}reset(){this.mode=0;this.D.reset(0);this.j.reset(1)}},XSx=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,
74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,
215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255],TZA=class{constructor(){this.type=0}set(A){this.type=A}get(){return this.type}},ST1=class{constructor(){this.state=this.Lw=this.LC=0}clear(){this.state=0}update(){this.state=this.state===2?1:0}QI(){return this.state!==0}matches(A,P){return this.QI()&&A===this.LC&&P===this.Lw}},J41=class{constructor(){this.timestamp=this.O=0}reset(){this.timestamp=
this.O=0}},WV=class{constructor(A){this.j=A;this.N=[];this.O=this.Y=this.row=0;this.style=new TZA;this.D=0;for(A=0;A<=15;A++){this.N[A]=[];for(let P=0;P<=32;P++)this.N[A][P]=new J41}}updateTime(A){for(let P=1;P<=15;++P)for(let D=1;D<=32;++D)this.N[P][D].timestamp=A}debugString(){var A="\n";for(let P=1;P<=15;++P){for(let D=1;D<=32;++D){let d=this.N[P][D];A=d.O===0?A+"_":A+String.fromCharCode(d.O)}A+="\n"}return A}reset(A){for(let P=0;P<=15;P++)for(let D=0;D<=32;D++)this.N[P][D].reset();this.D=A;this.O=
0;this.Y=this.row=1}},mQK=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],owA=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],ZST=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,
199,200,202,203,235,206,207,239,212,217,249,219,171,187],z_P=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499],LcP=class{constructor(A){this.N=A;this.j=0;this.style=new TZA;this.U=new WV(this.N);this.L=new WV(this.N);this.text=new WV(this.N);this.Y=this.U;this.D=this.L;this.O=this.Y}reset(A,P){this.j=P;this.style.set(2);this.Y=this.U;this.D=this.L;this.O=this.Y;var D=(A<<2)+(P<<1);this.U.reset(D);this.L.reset(D);this.text.reset((A<<
2)+(P<<1)+1)}},YTF=class{constructor(A){this.O=A;this.j=0;this.N=new LcP(this.O);this.U=new LcP(this.O);this.Y=new ST1;this.D=this.N}reset(A){this.j=A;this.Y.clear();this.D=this.N;this.N.reset(A,0);this.U.reset(A,1)}};var qTK=class{D(){}};var f5=class extends g.a3{reset(){}};var IQ=class extends g.ut{constructor(A,P,D,d,u){super(A,A+P,{priority:D,namespace:"captions"});this.id=d;this.params=u;this.O=[]}toString(){return super.toString()}},GX=0;var s3P=class extends f5{constructor(A){super();this.D=A;this.pens={};this.A={};this.Z={};this.j="_"+GX++;this.L={};this.Y=this.O=null;this.U=!0}reset(){this.L={};this.Y=this.O=null;this.U=!0}N(A,P){A=A.firstChild;A.getAttribute("format");P=P||0;Number.isFinite(P);A=Array.from(A.childNodes);for(var D of A)if(D.nodeType===1)switch(D.tagName){case "head":var d=D;break;case "body":var u=D}if(d){d=Array.from(d.childNodes);for(var B of d)if(B.nodeType===1)switch(B.tagName){case "pen":D=B.getAttribute("id");
d=this.pens;A={};var U=B.getAttribute("p");U&&Object.assign(A,this.pens[U]);U=Vl(B,"b");U!=null&&(A.bold=U);U=Vl(B,"i");U!=null&&(A.italic=U);U=Vl(B,"u");U!=null&&(A.underline=U);U=j$(B,"et");U!=null&&(A.charEdgeStyle=U);U=j$(B,"of");U!=null&&(A.offset=U);U=XQ(B,"bc");U!=null&&(A.background=U);U=XQ(B,"ec");U!=null&&(A.Cu=U);U=XQ(B,"fc");U!=null&&(A.color=U);U=j$(B,"fs");U!=null&&U!==0&&(A.fontFamily=U);U=p5(B,"sz");U!==void 0&&(A.fontSizeIncrement=U/100-1);U=p5(B,"bo");U!==void 0&&(A.backgroundOpacity=
U/255);U=p5(B,"fo");U!==void 0&&(A.textOpacity=U/255);U=j$(B,"rb");U!=null&&U!==10&&U!==0&&(A.I_=U>10?U-1:U);U=j$(B,"hg");U!=null&&(A.We=U);d[D]=A;break;case "ws":d=B.getAttribute("id");this.Z[d]=JVb(this,B);break;case "wp":d=B.getAttribute("id"),this.A[d]=LeF(this,B)}}if(u){B=[];u=Array.from(u.childNodes);for(p of u)if(p.nodeType===1)switch(p.tagName){case "w":this.O=q7T(this,p,P,!1);(u=this.L[this.O.id])&&u.end>this.O.start&&(u.end=this.O.start);this.L[this.O.id]=this.O;B.push(this.O);break;case "p":var c=
p;A=P;u=[];d=c.getAttribute("w")||this.j;D=!!Vl(c,"a");A=(p5(c,"t")||0)+A;U=p5(c,"d")||5E3;D||(!this.U&&this.Y&&this.Y.windowId===d&&this.Y.end>A&&(this.Y.end=A),this.Y&&this.Y.text==="\n"&&(this.Y.text=""));let b=D?6:5;var e=c.getAttribute("p");e=e?this.pens[e]:null;let F=Array.from(c.childNodes);F.length&&(this.U=c.getAttribute("d")!=null);for(c=0;c<F.length;c++){var H=F[c],k=void 0;c>0&&(D=!0);let Z;H.nodeType===1&&(Z=H);if(Z&&Z.tagName==="s"){if((H=(H=Z.getAttribute("p"))?this.pens[H]:null)&&
H.I_&&(H.I_===1?(H=F.slice(c,c+4),H.length===4&&(k=TQR(A,U,d,D,b,H,this.pens),c+=3)):k=TQR(A,U,d,D,b,[Z],this.pens)),!k){var l=Z;k=A;H=U;var Q=d,v=D;let z=l.textContent?l.textContent:"";var R=l.getAttribute("p");R=R?this.pens[R]:null;l=p5(l,"t")||0;k=new hk(k+l,H-l,b,Q,z,v,R)}}else k=new hk(A,U,b,d,H.textContent||"",D,e);u.push(k);this.Y=k}if(u.length>0){u[0].windowId===this.j&&(this.O=q7T(this,p,P,!0),B.push(this.O));for(let Z of u)Z.windowId=this.O.id,this.O.O.push(Z),B.push(Z)}}var p=B}else p=
[];return p}};var Wc1=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]),fZT=class extends f5{constructor(A){super();this.U=A;this.O=new Map;this.D=new Map;this.j=new Map;this.Y=new Map}reset(){this.Y.clear()}N(A,P){A=JSON.parse(A);if(!A)return[];if(A.pens){var D=A.pens,d=0;for(var u of D){D={};var B=u.pParentId;B&&Object.assign(D,this.O.get(B));u.bAttr&&(D.bold=!0);u.iAttr&&(D.italic=!0);u.uAttr&&(D.underline=!0);B=u.ofOffset;B!=null&&(D.offset=B);u.szPenSize!==void 0&&(D.fontSizeIncrement=u.szPenSize/100-1);
B=u.etEdgeType;B!=null&&(D.charEdgeStyle=B);u.ecEdgeColor!==void 0&&(D.Cu=n5(u.ecEdgeColor));B=u.fsFontStyle;B!=null&&B!==0&&(D.fontFamily=B);u.fcForeColor!==void 0&&(D.color=n5(u.fcForeColor));u.foForeAlpha!==void 0&&(D.textOpacity=u.foForeAlpha/255);u.bcBackColor!==void 0&&(D.background=n5(u.bcBackColor));u.boBackAlpha!==void 0&&(D.backgroundOpacity=u.boBackAlpha/255);(B=u.rbRuby)&&B!==10&&(D.I_=B>10?B-1:B,D.textEmphasis=Wc1.get(D.I_));u.hgHorizGroup&&(D.We=u.hgHorizGroup);this.O.set(d++,D)}}if(A.wsWinStyles){d=
A.wsWinStyles;u=0;for(var U of d)d={},(D=U.wsParentId)?Object.assign(d,this.j.get(D)):Object.assign(d,this.U),U.mhModeHint!==void 0&&(d.XX=U.mhModeHint),U.juJustifCode!==void 0&&(d.textAlign=U.juJustifCode),U.pdPrintDir!==void 0&&(d.JM=U.pdPrintDir),U.sdScrollDir!==void 0&&(d.il=U.sdScrollDir),U.wfcWinFillColor!==void 0&&(d.windowColor=n5(U.wfcWinFillColor)),U.wfoWinFillAlpha!==void 0&&(d.windowOpacity=U.wfoWinFillAlpha/255),this.j.set(u++,d)}if(A.wpWinPositions){u=A.wpWinPositions;U=0;for(var c of u)u=
{},(d=c.wpParentId)&&Object.assign(u,this.D.get(d)),c.ahHorPos!==void 0&&(u.tq=c.ahHorPos),c.apPoint!==void 0&&(u.Wz=c.apPoint),c.avVerPos!==void 0&&(u.gn=c.avVerPos),c.ccCols!==void 0&&(u.gJ=c.ccCols),c.rcRows!==void 0&&(u.tn=c.rcRows),this.D.set(U++,u)}if(A.events){A=A.events;c=[];for(let Y of A)if(U=(Y.tStartMs||0)+P,u=Y.dDurationMs||0,Y.id)d=String(Y.id),A=s$t(this,Y,U,u,d),c.push(A),this.Y.set(d,A);else{Y.wWinId?d=Y.wWinId.toString():(d="_"+GX++,A=s$t(this,Y,U,u,d),c.push(A),this.Y.set(d,A));
A=c;var e=Y;u===0&&(u=5E3);D=this.Y.get(d);let DD=(B=!!e.aAppend)?6:5,kQ=e.segs,M5=null;e.pPenId&&(M5=this.O.get(e.pPenId));for(e=0;e<kQ.length;e++){var H=kQ[e],k=H.utf8;if(k){var l=H.tOffsetMs||0;let xQ=null;H.pPenId&&(xQ=this.O.get(H.pPenId));if((D.params.XX!=null?D.params.XX:D.O.length>1?1:0)===2&&B&&k==="\n")continue;H=null;var Q=[],v;if(v=xQ&&xQ.I_===1)a:{v=kQ;var R=e;if(R+3>=v.length||!v[R+1].pPenId||!v[R+2].pPenId||!v[R+3].pPenId){v=!1;break a}var p=v[R+1].pPenId;(p=this.O.get(p))&&p.I_&&p.I_===
2?(p=v[R+2].pPenId,p=this.O.get(p),!p||!p.I_||p.I_<3?v=!1:(p=v[R+3].pPenId,v=(p=this.O.get(p))&&p.I_&&p.I_===2?!0:!1)):v=!1}if(v)l=kQ[e+1].utf8,H=kQ[e+3].utf8,v=kQ[e+2].utf8,R=this.O.get(kQ[e+2].pPenId),k=NQJ(k,l,v,H,R),H=new hk(U,u,DD,d,k,B,xQ),e+=3;else{if(k.indexOf("<")>-1){Q=xQ;v=M5;R=U;p=u;var b=l,F=DD,Z=B;let N5=[];var z=g.s4(`<html>${k}</html>`);if(!z.getElementsByTagName("parsererror").length&&z.firstChild?.childNodes.length)for(let AJ of z.firstChild.childNodes){z=AJ.textContent?.replace(/\n/g,
"")??"";if(AJ.nodeType===3&&(!z||z.match(/^ *$/)!=null))continue;let zN={};Object.assign(zN,Q||v);switch(AJ?.tagName){case "b":zN.bold=!0;break;case "i":zN.italic=!0;break;case "u":zN.underline=!0}N5.push(new hk(R+b,p-b,F,D.id,z,Z,zN))}Q=N5}Q.length||(Q=[new hk(U+l,u-l,DD,D.id,k,B,xQ||M5)])}if(Q.length)for(let N5 of Q)A.push(N5),D.O.push(N5);else H&&(A.push(H),D.O.push(H))}B=!0}}P=c}else P=[];return P}};var AsF=class extends g.Cl{constructor(A,P,D){super(A);this.videoData=P;this.audioTrack=D;this.Z=P.rX}D(A,P,D){ktF(this.videoData.videoId,A.vssId,D.oD)}j(A){if(this.audioTrack)for(let P of this.audioTrack.captionTracks)g.$N(this.O,P);A.Bk()}};var OvA=class extends sH{constructor(A,P,D,d,u,B,U,c,e,H){super(A,P,D,d,u,B,U,c,e,H);this.type=1}Le(A){var P=this.Y.O;super.Le(A);for(A=A.length;A<P.length;A++){let u=P[A],B;if(d&&u.O===D)B=d;else{B={};Object.assign(B,u.O);Object.assign(B,PVb);var D=u.O;var d=B}MLT(this,u,B)}}},PVb={mL:!0};var Wet=class extends qTK{constructor(A,P){super();this.trackData=A;this.U=P;this.version=this.j=this.N=this.byteOffset=0;this.Y=[];this.O=new DataView(this.trackData)}D(A,P,D,d,u){if(D<d){let B="_"+GX++;D=D/1E3-this.U;d=d/1E3-this.U;A=new IQ(D,d-D,5,B,{textAlign:0,Wz:0,tq:P*2.5,gn:A*5.33});u=new hk(D,d-D,5,B,u);this.Y.push(A);this.Y.push(u)}}},D9b=class extends f5{constructor(A,P){super();this.Y=A;this.D=P;this.track=this.D.languageName==="CC3"?4:0;this.O=new NZJ;this.O.Y=1<<this.track}N(A){A=new Wet(A,
this.Y);if(fYx(A)){for(;A.byteOffset<A.O.byteLength;)for(A.version===0?A.N=OH(A)*(1E3/45):A.version===1&&(A.N=OH(A)*4294967296+OH(A)),A.j=bu(A);A.j>0;A.j--){var P=bu(A);let D=bu(A),d=bu(A);P&4&&(P&3)===this.track&&(this.track===0||this.track===1)&&(P=this.O,P.O.push({time:A.N,type:this.track,NR:D,RC:d,order:P.O.length}))}Fey(this.O,A);return A.Y}return[]}reset(){this.O.clear()}};var FcT=class extends sH{constructor(A,P,D,d,u,B,U,c,e,H){super(A,P,D,d,u,B,U,c,e,H);this.type=2;this.b8=[];this.Hy=this.OC=this.UC=0;this.xi=NaN;this.gO=0;this.SZ=null;this.AX=new g.jp(this.I2,433,this);this.U&&(H.createClientVe(this.U,this,167342),this.V(this.U,"click",()=>{H.logClick(this.U)}),A=new g.JK(this.element,!0),g.V(this,A),A.subscribe("hoverstart",()=>{H.logVisibility(this.U,!0)},this));
g.mR(this.element,"ytp-caption-window-rollup");g.V(this,this.AX);g.Fs(this.element,"overflow","hidden")}yq(){g.XH(this.AX)}I2(){this.element.removeEventListener("transitionend",this.I2,!1);g.Zn(this.element,"ytp-rollup-mode");this.A(this.SZ,!0)}Vq(){return this.D?this.Hy:this.OC}K$(){return this.D?this.OC:this.Hy}A(A,P){this.SZ=A;if(this.Y.params.tn){var D=0;for(let d=0;d<this.L.length&&D<A.length;d++)this.L[d]===A[D]&&D++;D>0&&D<A.length&&(A=this.L.concat(A.slice(D)));this.gO=this.Hy;this.OC=this.Hy=
0;super.A(A);dRA(this,P)}super.A(A)}};var d9P=class{constructor(A,P,D,d){this.K=A;this.j=P;this.logger=D;this.Qq=d;this.rI=[];this.O=null;this.N=[];this.ix=[];this.Y=null;this.wO={F4N:()=>this.Y,
Xy:()=>this.rI,
b_2:u=>{this.N=u},
Yg_:()=>this.N};
A=g.jz(this.K.G().experiments,"html5_override_micro_discontinuities_threshold_ms");this.D=A>0?A:10}unload(){this.Y!=null&&(this.K.removeEventListener("sabrCaptionsDataLoaded",this.Y),this.Y=null);this.rI=[];this.O=null;this.N=[];this.K.publish("sabrCaptionsBufferedRangesUpdated",this.rI)}uw(A){return{formatId:g.Vk(A.info.TN.info,this.Qq),sC:A.info.sC+(this.Qq?0:1),startTimeMs:A.info.N*1E3,durationMs:A.info.L*1E3}}};var uiA=class extends g.Cl{constructor(A,P){super(P);this.Y=A;this.K=P;this.logger=new g.Qk("caps");this.A=this.Hy=null;this.Yi=new d9P(this.K,this,this.logger,this.Y.Qq)}D(A,P,D){this.N();P=A.getId();P=P!=null&&P in this.Y.O?this.Y.O[P]:null;P||(P=A.languageCode,P=this.Y.isManifestless?Hvt(this,P,"386"):Hvt(this,P));P&&(this.A=A,this.Hy=P,eot(this.Yi,D),this.K.publish("sabrCaptionsTrackChanged",g.Vk(P.info,this.Y.Qq)))}j(A){var P=this.Y.isManifestless?$RJ(this,"386"):$RJ(this);for(let D of P)g.$N(this.O,
D);A.Bk()}N(){this.A&&(this.A=this.Hy=null,this.Yi.unload(),this.K.publish("sabrCaptionsTrackChanged",null))}U(){return""}};var g2A="WEBVTT".split("").map(A=>A.charCodeAt(0)),t9x=class extends f5{constructor(){super()}N(A,P){A instanceof ArrayBuffer&&(A=g.V_(new Uint8Array(A)));
var D=[];A=A.split(ByJ);for(let R=1;R<A.length;R++){var d=A[R],u=P;if(d!==""&&!U9K.test(d)){var B=AR.exec(d);if(B&&B.length>=4){var U=FQ(B[1]),c=FQ(B[2])-U;U+=u;var e=(B=B[3])?B.split(" "):[];B={};var H=null;var k="";var l=null,Q="";for(let p of e){e=p.split(":");if(e.length!==2)continue;var v=e[1];switch(e[0]){case "line":e=v.split(",");e[0].endsWith("%")&&(H=e[0],B.gn=Number.parseInt(H,10),e.length===2&&(k=e[1].trim()));break;case "position":e=v.split(",");l=e[0];B.tq=Number.parseInt(l,10);e.length===
2&&(Q=e[1].trim());break;case "align":switch(v){case "start":B.textAlign=0;break;case "middle":B.textAlign=2;break;case "end":B.textAlign=1}}}H||k||(k="end");if(!l)switch(B.textAlign){case 0:B.tq=0;break;case 1:B.tq=100;break;case 2:B.tq=50}if(B.textAlign!=null){H=0;switch(k){case "center":H+=3;break;case "end":H+=6;break;default:H+=0}switch(Q){case "line-left":H+=0;break;case "center":H+=1;break;case "line-right":H+=2;break;default:switch(B.textAlign){case 0:H+=0;break;case 2:H+=1;break;case 1:H+=
2}}k=H<0||H>8?7:H;B.Wz=k}d=d.substring(AR.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");Q=B;B={};if(d.indexOf("<")<0&&d.indexOf("&")<0)u=lZJ(U,c,5,Q),U=new hk(U,c,5,u.id,d,!1,g.SF(B)?void 0:B),D.push(u),D.push(U),u.O.push(U);else for(k=d.split(cs1),k.length===1?(d=5,Q=lZJ(U,c,d,Q)):(H=d=6,Q=Object.assign({gJ:32},Q),Q=new IQ(U,c,H,"_"+GX++,Q)),D.push(Q),H=U,l=0;l<k.length;l++)if(e=k[l],l%2===0){v=g.s4(`<html>${e}</html>`);let p;v.getElementsByTagName("parsererror").length?(p=v.createElement("span"),
p.appendChild(v.createTextNode(e))):p=v.firstChild;Q3t(this,H,c-(H-U),d,Q,l>0,p,B,D)}else H=FQ(e)+u}AR.lastIndex=0}}return D}},U9K=/^NOTE/,ByJ=/(?:\r\n|\r|\n){2,}/,AR=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),cs1=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");var eQA=class extends g.a3{constructor(A,P){super();this.K=A;this.X=P;this.O=null;this.JX=this.K.n8();this.logger=new g.Qk("caps")}clear(){this.O&&this.O.dispose();this.O=null}reset(){this.O&&this.O.reset()}Nd(){super.Nd();this.clear()}};var xRK={windowColor:"#080808",windowOpacity:0,textAlign:2,Wz:7,tq:50,gn:100,isDefault:!0,Wn:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}},w$T={windowColor:"#080808",windowOpacity:0,textAlign:0,Wz:7,tq:50,gn:100,isDefault:!0,Wn:{background:"#080808",backgroundOpacity:.7,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.H4("captions",class extends g.zy{constructor(A){super(A);this.K=A;this.xi=[];this.hG={};this.y_={};this.L=!1;this.N="NONE";this.O=this.Z=this.Yi=this.UC=this.Md=null;this.ZL={Bk:()=>{this.Bk()},
oD:(d,u,B,U,c=0)=>{var e=Number(this.videoData.G().EC().O.tG(g.T0M)??0);c>0&&e>0&&this.videoData.lengthSeconds>0&&c/this.videoData.lengthSeconds>e?this.K.F9("tts",{dropcap:c}):this.oD(d,u,B,U)}};
this.Y=null;this.Ns="";this.X=this.K.G();this.videoData=this.K.getVideoData();this.I2=this.K.lf();this.j={Wn:{}};this.U={Wn:{}};this.videoData.sH()?this.N="OFFLINE":g.Yh5(this.videoData,this.K)?this.N="HLS":ivt(this.videoData,this.K)?this.N="SABR_LIVE":g.NVD(this.videoData,this.K)?this.N="LIVE":this.videoData.captionTracks.length?this.N="INNERTUBE":this.videoData.Ru&&(this.N="TTS");this.ki=this.X.controlsType==="3";this.Le=new eQA(this.K,this.X);this.b8=new g.R9(this);this.A=new g.W({C:"div",J:"ytp-caption-window-container",
W:{id:"ytp-caption-window-container"}});this.Hy={top:0,right:0,bottom:0,left:0,width:1,height:1};var P=null,D=g.Qj("yt-html5-player-modules::subtitlesModuleData");D&&(P=new g.UJ(D));this.storage=P;P=A.gI();this.Ru=!!P?.xi();this.SH=!!P?.eH();this.D=mi(this);this.OC=RoK(this);g.V(this,this.Le);this.D?this.Ce=this.eH=null:(this.eH=new g.Vg(this.jZ,void 0,this),g.V(this,this.eH),this.Ce=new g.jp(this.AX,2E3,this),g.V(this,this.Ce));g.V(this,this.b8);g.Jg(this.player,this.A.element,4);g.V(this,this.A);
this.D||this.b8.V(A,"resize",this.OH);P=g.x9(this.X)&&!g.zV()&&!this.K.isFullscreen();D=this.X.EC().O.tG(g.ij4)&&g.l7(this.X)==="MWEB"&&g.LD;(this.sH=(P||D)&&!this.D&&!this.OC)&&this.b8.V(A,P?"resize":"fullscreentoggled",this.K$);this.b8.V(A,"onPlaybackAudioChange",this.Vq);this.b8.V(A,g.is("captions"),d=>{this.onCueRangeEnter(d)});
this.b8.V(A,g.Hk("captions"),d=>{this.onCueRangeExit(d)});
oQ(this,vV()||{});g.Xf(this.player,"onCaptionsModuleAvailable");this.N==="HLS"&&this.D&&(A=this.K.gI().cD(),this.SH&&this.b8.V(A.textTracks,"addtrack",this.gO))}Nd(){if(this.D||this.OC){let A=this.K.gI();A&&!A.Q_()&&A.L()}else Z0(this,!1);super.Nd()}O_(){return this.X.B("html5_honor_caption_availabilities_in_audio_track")&&this.N!=="LIVE"&&this.N!=="SABR_LIVE"}Lc(){if(this.ki)return this.D||this.OC;if(this.N==="HLS")return this.D;var A=this.getAudioTrack();if(this.O_()){if(!A.captionTracks.length)return!1;
if(!this.O)return!0}A=lu(A,g.FL(this.X));return A==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:A==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?rS(this):EH(this)||rS(this)?!0:p$F(this)}load(){super.load();this.Z=this.getAudioTrack();if(this.O)this.Y&&(this.Le.clear(),this.D?V9J(this,!0):this.player.getPresentingPlayerType()!==3&&this.O.D(this.Y,"json3",this.ZL),this.N!=="HLS"&&this.D||this.OC||YP(this)||g.Xf(this.player,"captionschanged",g.EG(this.Y)));else{let A;this.N==="OFFLINE"?A=new AsF(this.player,this.videoData,
this.getAudioTrack()):this.N==="SABR_LIVE"?A=new uiA(this.videoData.O,this.player):this.N==="HLS"?A=new Zvx(this.player):this.N==="LIVE"?A=new E2F(this.videoData.O,this.player):this.N==="INNERTUBE"?A=new g.Ea(this.player,this.videoData,this.getAudioTrack()):A=new g.rO(this.player,this.videoData.Ru,this.videoData.videoId,g.n_9(this.videoData),this.videoData.G9,this.videoData.eventId);this.O=A;g.V(this,this.O);this.O.j(this.ZL)}}unload(){this.D&&this.Y?V9J(this,!1):(this.Ce&&this.Ce.El(),this.player.kX("captions"),
this.xi=[],this.O&&this.O.N(),this.Le.clear(),this.Yi&&this.player.ZR(this.Yi),this.OH());super.unload();this.player.h0();g.Xf(this.player,"captionschanged",{})}create(){this.Lc()&&this.load();var A;a:{if(this.X.B("web_player_nitrate_promo_tooltip")&&this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.enableTouchCaptionsNitrate&&(A=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.captionTracks))for(let P of A)if(P.kind==="asr"&&P.languageCode===
"en"){A=!0;break a}A=!1}A&&this.K.publish("showpromotooltip",this.A.element)}Bk(){var A=lu(this.player.getAudioTrack(),g.FL(this.X));var P=A==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?TX(this,this.L):A==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&rS(this)?NK(this):EH(this)||this.L||p$F(this)?TX(this,this.L):rS(this)?NK(this):null;if(this.N!=="HLS"&&this.D||this.OC){let D=g.Yz(this.O.O,!0);A=[];for(let d=0;d<D.length;d++){let u=D[d],B=g.cv("TRACK");B.setAttribute("kind","subtitles");B.setAttribute("label",
g.CH(u));B.setAttribute("srclang",g.r7(u));B.setAttribute("id",u.toString());this.OC||B.setAttribute("src",this.O.U(u,"vtt"));u===P&&B.setAttribute("default","1");A.push(B)}P=this.K.gI();P.Yi(A);A=P.cD();this.SH&&this.b8.V(A.textTracks,"change",this.yq)}else!this.Y&&P&&qK(this,P),g.Xf(this.player,"onCaptionsTrackListChanged"),g.nc(this.player,"onApiChange")}getTrackById(A){var P=g.Yz(this.O.O,!0);for(let D=0;D<P.length;D++)if(P[D].toString()===A)return P[D];return null}yq(){var A=this.K.gI().cD().textTracks,
P=null;for(let D=0;D<A.length;D++)A[D].mode==="showing"&&(P=this.getTrackById(A[D].id));(this.loaded?this.Y:null)!==P&&qK(this,P,!0)}gO(){this.O?.j(this.ZL)}DK(){!this.Y&&this.D||this.unload()}oD(A,P,D,d){if(A){L5(this,this.Y??void 0);this.O.OC()&&(this.xi=[],this.K.kX("captions"),kP(this.eH),this.Le.reset());a:{var u=this.Le;d=d||0;D=Kcx(u,A,D||0);A=[];try{for(let F of D){let Z=F.trackData,z=F.yA,Y=u.X.B("safari_live_drm_captions_fix");if(typeof Z!=="string"){D=A;var B=D.concat;if(Y&&k5q(Z))var U=
y4t(u,Z,z);else{var c=u,e=P,H=Z,k=z,l=d;if(!A4y(H))throw Error("Invalid binary caption track data");c.O||(c.O=new D9b(l,e));U=c.O.N(H,k)}var Q=B.call(D,U)}else{if(Z.substring(0,6)==="WEBVTT")var v=A.concat(y4t(u,Z,z));else{D=A;var R=D.concat;b:{e=u;c=P;if(Z[0]==="{")try{e.O||(e.O=new fZT(aZy(c)));var p=e.O.N(Z,z);break b}catch(M5){g.KK(M5);p=[];break b}let DD=g.s4(Z);if(!DD||!DD.firstChild){let M5=Error("Invalid caption track data");M5.params=Z;throw M5;}if(DD.firstChild.tagName==="timedtext"){if(Number(DD.firstChild.getAttribute("format"))===
3){H=DD;e.O||(e.O=new s3P(aZy(c)));p=e.O.N(H,z);break b}let M5=Error("Unsupported subtitles format in web player (Format2)");M5.params=Z;throw M5;}if(DD.firstChild.tagName==="transcript"){let M5=Error("Unsupported subtitles format in web player (Format1)");M5.params=Z;throw M5;}let kQ=Error("Invalid caption track data");kQ.params=Z;throw kQ;}v=R.call(D,p)}Q=v}A=Q}var b=A;break a}catch(F){g.vc(u.logger,187101178,`Captions parsing failed: ${F.message}. `);u.clear();b=[];break a}b=void 0}this.X.B("html5_sabr_live_support_subfragmented_captions")&&
this.O instanceof uiA&&(P=this.O.Yi,u=[],b.length>0&&(u=b.slice(P.N.length)),P.N=!P.O||P.O.info.Pn?[]:b,b=u);P=this.X.EC().O.tG(g.WhJ);b.length>0&&(!P||this.Ns!==this.Y?.Y())&&(u=this.Y,this.jY(u,!!u,YP(this)?"g":this.L?"m":"s"),P&&(this.Ns=this.Y?.Y()||""));this.player.ZR(b,void 0,this.N==="LIVE"||this.N==="SABR_LIVE");!this.L||this.OC||YP(this)||g.L2(this.X)||g.wH(this.X)||g.F8(this.X)||this.X.Hy==="shortspage"||this.player.isInline()||(this.Ce.El(),b=S7A({Wz:0,tq:5,gn:5,tn:2,textAlign:0,JM:0,lang:"en"}),
this.UC=[b],P=["Click "," for settings"],this.Md||(u=new g.mE(g.lJ()),g.V(this,u),this.Md=u.element),u=b.end-b.start,(Q=g.CH(this.Y))&&this.UC.push(new hk(b.start,u,0,b.id,Q)),this.UC.push(new hk(b.start,u,0,b.id,P[0]),new hk(b.start,u,0,b.id,this.Md,!0),new hk(b.start,u,0,b.id,P[1],!0)),this.player.ZR(this.UC),g.MA(this.Ce));!this.L||this.OC||YP(this)||(this.X.B("enable_player_captions_persistence_state_machine")?C5(this,!0):g.FL(this.X)?S$(this,!0):Jk(this,!0),this.Z&&(this.Z.D=this.Y),this.player.h0());
this.L=!1}}onCueRangeEnter(A){this.xi.push(A);kP(this.eH)}onCueRangeExit(A){g.ly(this.xi,A);this.O instanceof E2F&&this.O.Hy&&this.player.mh([A]);kP(this.eH)}getCaptionWindowContainerId(){return this.A.element.id}AX(){hoT(this,this.UC);this.UC=null}jZ(){if(!this.sH||!this.D){this.eH.stop();g.JJ(this.y_);this.xi.sort(g.ec);var A=this.xi;if(this.Yi){let P=g.Pq(A,function(D){return this.Yi.indexOf(D)===-1},this);
P.length&&(A=P)}for(let P of A)P instanceof IQ?X$t(this,P):n2b(this,P);for(let [P,D]of Object.entries(this.hG)){let d=P,u=D;this.y_[d]?(u.element.parentNode||(u instanceof FcT||u instanceof OvA||g.Fx(this.hG,(B,U)=>{U!==d&&B.Y.params.Wz===u.Y.params.Wz&&B.Y.params.tq===u.Y.params.tq&&B.Y.params.gn===u.Y.params.gn&&(B.dispose(),delete this.hG[U]);return U===d},this),this.A.element.appendChild(u.element)),u.A(this.y_[d])):(u.dispose(),delete this.hG[d])}}}Tp(){oQ(this,{},!0);
g.Xf(this.player,"captionssettingschanged")}UW(){var A=this.X.B("enable_player_captions_new_style_defaults")?w$T:xRK,P=A.Wn;A={background:P.background,backgroundOpacity:P.backgroundOpacity,charEdgeStyle:P.charEdgeStyle,color:P.color,fontFamily:P.fontFamily,fontSizeIncrement:P.fontSizeIncrement,fontStyle:P.bold&&P.italic?3:P.bold?1:P.italic?2:0,textOpacity:P.textOpacity,windowColor:A.windowColor,windowOpacity:A.windowOpacity};P=vV()||{};P.background!=null&&(A.background=P.background);P.backgroundOverride!=
null&&(A.backgroundOverride=P.backgroundOverride);P.backgroundOpacity!=null&&(A.backgroundOpacity=P.backgroundOpacity);P.backgroundOpacityOverride!=null&&(A.backgroundOpacityOverride=P.backgroundOpacityOverride);P.charEdgeStyle!=null&&(A.charEdgeStyle=P.charEdgeStyle);P.charEdgeStyleOverride!=null&&(A.charEdgeStyleOverride=P.charEdgeStyleOverride);P.color!=null&&(A.color=P.color);P.colorOverride!=null&&(A.colorOverride=P.colorOverride);P.fontFamily!=null&&(A.fontFamily=P.fontFamily);P.fontFamilyOverride!=
null&&(A.fontFamilyOverride=P.fontFamilyOverride);P.fontSizeIncrement!=null&&(A.fontSizeIncrement=P.fontSizeIncrement);P.fontSizeIncrementOverride!=null&&(A.fontSizeIncrementOverride=P.fontSizeIncrementOverride);P.fontStyle!=null&&(A.fontStyle=P.fontStyle);P.fontStyleOverride!=null&&(A.fontStyleOverride=P.fontStyleOverride);P.textOpacity!=null&&(A.textOpacity=P.textOpacity);P.textOpacityOverride!=null&&(A.textOpacityOverride=P.textOpacityOverride);P.windowColor!=null&&(A.windowColor=P.windowColor);
P.windowColorOverride!=null&&(A.windowColorOverride=P.windowColorOverride);P.windowOpacity!=null&&(A.windowOpacity=P.windowOpacity);P.windowOpacityOverride!=null&&(A.windowOpacityOverride=P.windowOpacityOverride);return A}U2(A,P){var D={};Object.assign(D,vV());Object.assign(D,A);oQ(this,D,P);g.Xf(this.player,"captionssettingschanged")}OH(){!this.D&&this.loaded&&(g.nP(this.hG,function(A,P){A.dispose();delete this.hG[P]},this),this.jZ())}SY(A,P){switch(A){case "fontSize":if(isNaN(P))break;
A=g.j5(P,-2,4);this.U2({fontSizeIncrement:A});return A;case "reload":P&&!this.D&&qK(this,this.Y,!0);break;case "stickyLoading":P!==void 0&&this.X.A&&(this.X.B("enable_player_captions_persistence_state_machine")?C5(this,!(!P||!P.userInitiated)):g.FL(this.X)?S$(this,!!P):Jk(this,!!P));break;case "track":return mR1(this,P);case "tracklist":return this.O?g.Dt(g.Yz(this.O.O,!(!P||!P.includeAsr)),D=>g.EG(D)):[];
case "translationLanguages":return this.O?this.O.Z.map(D=>Object.assign({},D)):[];
case "sampleSubtitles":this.D||P===void 0||Z0(this,!!P);break;case "sampleSubtitlesCustomized":this.D||Z0(this,!!P,P);break;case "recommendedTranslationLanguages":return g.FZ();case "defaultTranslationSourceTrackIndices":return this.O?this.O.hG:[]}}getOptions(){var A="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.A&&A.push("stickyLoading");return A}Yh(){var A=this.Y;if(this.K.hH("captions")){if(this.X.B("html5_modify_caption_vss_logging"))return(A=this.videoData.eB??
null)?{cc:g.IaQ(A)}:{};if(A){let P=A.vssId;A.translationLanguage&&P&&(P=`t${P}.${g.r7(A)}`);return{cc:P}}}return{}}X7(A){this.isSubtitlesOn()?(this.X.B("enable_player_captions_persistence_state_machine")&&A?C5(this,!1):g.FL(this.X)?S$(this,!1):Jk(this,!1),L5(this),qK(this,null,!0)):this.Fj(A)}Fj(A){var P=YP(this)||!this.Y?TX(this,!0):this.Y;P&&this.tW(P.vssId,"m");this.isSubtitlesOn()||qK(this,P,this.X.B("enable_player_captions_persistence_state_machine")?A:!0)}isSubtitlesOn(){return!!this.loaded&&
!!this.Y&&!YP(this)}Vq(){var A=YP(this);rS(this,A)?qK(this,this.getAudioTrack().O,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.O_()&&(this.L=!1,this.Y=null,this.O&&(this.O.dispose(),this.O=null)),this.Lc()&&(A?qK(this,TX(this,!1),!1):this.load()))}W_(A){A&&(this.Hy={top:A.top,right:A.right,bottom:A.bottom,left:A.left,width:1-A.left-A.right,height:1-A.top-A.bottom},this.A.element.style.top=`${this.Hy.top*100}%`,this.A.element.style.left=`${this.Hy.left*100}%`,this.A.element.style.width=
`${this.Hy.width*100}%`,this.A.element.style.height=`${this.Hy.height*100}%`,this.A.element.style.position="absolute",A=bvA(this))&&(this.A.element.style.width=`${A.width}px`,this.A.element.style.height=`${A.height}px`)}onVideoDataChange(A,P){A==="newdata"&&(this.videoData=P,this.loaded&&this.unload(),this.L=!1,this.Y=null,this.O&&(this.O.dispose(),this.O=null,g.Xf(this.player,"captionschanged",{})),this.Lc()&&this.load())}getAudioTrack(){return this.player.getAudioTrack()}K$(){if(this.X.EC().O.tG(g.ij4)){if(this.loaded&&
this.unload(),this.ki=this.K.isFullscreen()||this.X.controlsType==="3",this.D=mi(this),this.OC=RoK(this),this.D||this.OC){var A=this.K.gI();A&&!A.Q_()&&A.L();this.Bk()}}else(A=this.K.gI())&&!A.Q_()&&A.L(),this.K.isFullscreen()?(this.D=this.ki=!0,this.loaded&&this.Bk()):(this.ki=this.X.controlsType==="3",this.D=mi(this));qK(this,this.Y)}gM(){var A=this.videoData.getPlayerResponse()?.captions?.playerCaptionsTracklistRenderer?.openTranscriptCommand;A&&g.pc(this.player,"innertubeCommand",A)}jY(A,P,D){var d=
/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,u="";A&&(u=A.vssId,u=u.replace(d,""));var B="";if(A&&A.getId()&&this.X.EC().O.tG(g.WhJ))if(B=A.getId()||"",B.includes(";"))B=B.split(";").map(c=>c.replace(d,"")).join(";");
else{B=B.replace(d,"");var U="";A.getXtags()&&(U=A.getXtags(),U=U.replace(d,""),B=B.concat(`;${U}`))}else A&&A.getId()&&(B=A.getId()||""),U="",A&&A.getXtags()&&(U=A.getXtags(),U=U.replace(d,""),B=B.concat(`;${U}`));this.N==="HLS"&&(B="");this.K.jY(P?u:"",P?B:"",D)}tW(A,P){A=(A||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");A.length>0&&this.K.tW(A,P)}});})(_yt_player);
