(function(g){var window=this;'use strict';var XwF=function(A,P){g.pc(A,"onAutonavCoundownStarted",P)},nxT=function(A){return A.isBackground()&&A.rE()},b7T=function(A,P){P=P.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.nextButton?.buttonRenderer;
A.OC=P?.navigationEndpoint;P=P?.trackingParams;A.playButton&&P&&A.K.setTrackingParams(A.playButton.element,P)},$L=function(A){var P=ip(A),D=Math,d=D.min;
var u=A.L?Date.now()-A.L:0;D=d.call(D,u,P);HA(A,Math.ceil((P-D)/1E3));P-D<=500&&A.O()?A.select(!0):A.O()&&A.A.start()},g0=function(A){var P=A.K.RZ(!0,A.K.isFullscreen());
g.Cp(A.container.element,"ytp-autonav-endscreen-small-mode",A.Uv(P));g.Cp(A.container.element,"ytp-autonav-endscreen-is-premium",!!A.suggestion&&!!A.suggestion.yO);g.Cp(A.K.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!A.K.rj());g.Cp(A.K.getRootNode(),"countdown-running",A.O());g.Cp(A.container.element,"ytp-player-content",A.K.rj());A.K.B("web_post_play_autonav_embiggening")||g.Fs(A.overlay.element,{width:`${P.width}px`});if(A.K.B("web_post_play_autonav_embiggening")){var D=A.K.getRootNode().getBoundingClientRect();
P=Math.min(720,D.width*.5);var d=P*.5625;D=D.height-36-60;d>D&&(d=D,P=16/9*d);g.Fs(A.Y.jH("ytp-autonav-endscreen-upnext-thumbnail"),{height:`${d}px`,width:`${P}px`});g.Fs(A.container.element,{width:`${P}px`})}A.O()||(A.K.rj()?HA(A,Math.round(ip(A)/1E3)):HA(A),P=!!A.suggestion&&!!A.suggestion.V6,d=A.K.getVideoData(),d=d?.autonavState===1&&d?.sB&&A.K.rj()?!1:A.K.rj()||!(A.suggestion&&A.suggestion.V6),g.Cp(A.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!d&&P),g.Cp(A.container.element,
"ytp-autonav-endscreen-upnext-no-alternative-header",d&&!P),A.U.ou(A.K.rj()))},HA=function(A,P=-1){A=A.Y.jH("ytp-autonav-endscreen-upnext-header");
g.Hv(A);if(P>=0){P=String(P);let D="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(D);if(d>=0){A.appendChild(g.eW("Up next in $SECONDS".slice(0,d)));let u=g.cv("span");g.Os(u,"ytp-autonav-endscreen-upnext-header-countdown-number");g.lA(u,P);A.appendChild(u);A.appendChild(g.eW("Up next in $SECONDS".slice(d+D.length)));return}}g.lA(A,"Up next")},ip=function(A){return A.K.isFullscreen()?(A=A.K.getVideoData()?.u5,A===-1||A===void 0?8E3:A):A.K.Xv()>=0?A.K.Xv():
g.jz(A.K.G().experiments,"autoplay_time")||1E4},kL=function(A,P){P=O7t(A,P);
var D=Math,d=D.min;var u=(0,g.N)()-A.L;D=d.call(D,u,P);P=P===0?1:Math.min(D/P,1);A.xi.setAttribute("stroke-dashoffset",`${-211*(P+1)}`);P>=1&&A.O()&&!A.isCasting()?A.select(!0):A.O()&&A.Y.start()},O7t=function(A,P){return P?P:A.api.isFullscreen()?(A=A.api.getVideoData()?.u5,A===-1||A===void 0?8E3:A):A.api.Xv()>=0?A.api.Xv():g.jz(A.api.G().experiments,"autoplay_time")||1E4},lp=function(A){return g.Lc(A.player)&&A.A()&&!A.D},QD=function(A){var P=A.rj();
P!==A.Z&&(A.Z=P,A.player.publish("autonavvisibility"))},vA=function(A){return g.Lc(A.player)&&A.A()&&!A.j},Kq=function(A){var P=A.rj();
P!==A.Hy&&(A.Hy=P,A.player.publish("autonavvisibility"))},F8F=function(A){A=A.G();
return A.AX&&!A.disableOrganicUi},m9y=function(A){var P=A.player.getVideoData();
if(!P||A.O===P.jZ)return!1;A.O=P.jZ;return!0},oxx=function(A){A.player.kX("endscreen");
var P=A.player.getVideoData();P=new g.ut(Math.max((P.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var D=new g.ut(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});A.player.ZR([P,D])};
g.Kl.prototype.Xv=g.Q9(16,function(){return this.app.Xv()});
g.d8.prototype.Xv=g.Q9(15,function(){return this.getVideoData().d9});
g.v8.prototype.oI=g.Q9(14,function(A){this.vJ().oI(A)});
g.dl.prototype.oI=g.Q9(13,function(A){this.mI!==A&&(this.mI=A,this.q7())});
var tR=class extends g.W{constructor(A){super({C:"div",J:"ytp-autonav-endscreen-countdown-overlay"});this.cancelCommand=this.OC=void 0;this.L=0;A.B("web_post_play_autonav_embiggening")&&g.mR(this.element,"ytp-autonav-endscreen-upnext-updated");this.container=new g.W({C:"div",J:"ytp-autonav-endscreen-countdown-container"});g.V(this,this.container);this.container.i8(this.element);var P=A.G(),D=P.N;this.K=A;this.suggestion=null;this.onVideoDataChange("newdata",this.K.getVideoData());this.V(A,"videodatachange",
this.onVideoDataChange);this.Y=new g.W({C:"div",J:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{C:"div",J:"ytp-autonav-endscreen-topbar-container",S:[{C:"div",J:"ytp-autonav-endscreen-upnext-header"},{C:"div",J:"ytp-autonav-endscreen-upnext-alternative-header",R2:"{{autoplayAlternativeHeader}}"}]},{C:"a",J:"ytp-autonav-endscreen-link-container",
W:{href:"{{url}}",target:D?P.Yi:""},S:[{C:"div",J:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},S:[{C:"div",W:{"aria-label":"{{timestamp}}"},rM:["ytp-autonav-timestamp"],R2:"{{duration}}"},{C:"div",rM:["ytp-autonav-live-stamp"],R2:"Live"},{C:"div",rM:["ytp-autonav-upcoming-stamp"],R2:"Upcoming"}]},{C:"div",J:"ytp-autonav-endscreen-video-info",S:[{C:"div",J:"ytp-autonav-endscreen-premium-badge"},{C:"div",J:"ytp-autonav-endscreen-upnext-title",R2:"{{title}}"},{C:"div",J:"ytp-autonav-endscreen-upnext-author",
R2:"{{author}}"},{C:"div",J:"ytp-autonav-view-and-date",R2:"{{views_and_publish_time}}"},{C:"div",J:"ytp-autonav-author-and-view",R2:"{{author_and_views}}"}]}]}]});g.V(this,this.Y);this.Y.i8(this.container.element);D||this.V(this.Y.jH("ytp-autonav-endscreen-link-container"),"click",this.b8);this.K.createClientVe(this.container.element,this,115127);this.K.createClientVe(this.Y.jH("ytp-autonav-endscreen-link-container"),this,115128);this.closeButton=new g.W({C:"button",J:"ytp-autonav-endscreen-upnext-header-close-button",
W:{"aria-label":"Cancel autoplay"}});g.V(this,this.closeButton);A.B("web_post_play_autonav_embiggening")&&(this.closeButton.listen("click",this.hG,this),this.K.createClientVe(this.closeButton.element,this,115129),this.Y.jH("ytp-autonav-endscreen-topbar-container").appendChild(this.closeButton.element));this.overlay=new g.W({C:"div",J:"ytp-autonav-overlay"});g.V(this,this.overlay);this.overlay.i8(this.container.element);this.U=new g.W({C:"div",J:"ytp-autonav-endscreen-button-container"});g.V(this,
this.U);this.U.i8(this.container.element);this.cancelButton=new g.W({C:"button",rM:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],W:{"aria-label":"Cancel autoplay"},R2:"Cancel"});g.V(this,this.cancelButton);this.cancelButton.i8(this.U.element);this.cancelButton.listen("click",this.hG,this);this.K.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.W({C:"a",rM:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},R2:"Play Now"});g.V(this,this.playButton);this.playButton.i8(this.U.element);this.playButton.listen("click",this.b8,this);this.K.createServerVe(this.playButton.element,this.playButton,!0);(P=this.K.getVideoData())&&b7T(this,P);this.A=new g.jp(()=>{$L(this)},500);
g.V(this,this.A);this.Hy();this.V(A,"autonavvisibility",this.Hy)}Z(A){this.suggestion!==A&&(this.suggestion=A,g.qI(this.Y,A),this.playButton.updateValue("url",this.suggestion.LN()),g0(this))}O(){return this.L>0}j(){this.O()||(this.L=Date.now(),$L(this),XwF(this.K,ip(this)),g.Cp(this.K.getRootNode(),"countdown-running",this.O()))}D(){this.N();$L(this);var A=this.Y.jH("ytp-autonav-endscreen-upnext-header");A&&g.lA(A,"Up next")}N(){this.O()&&(this.A.stop(),this.L=0)}select(A=!1){this.K.nextVideo(!1,
A);this.N()}b8(A){g.eh(A,this.K)&&(A.currentTarget===this.playButton.element?this.K.logClick(this.playButton.element):A.currentTarget===this.Y.jH("ytp-autonav-endscreen-link-container")&&(A=this.Y.jH("ytp-autonav-endscreen-link-container"),this.K.logVisibility(A,!0),this.K.logClick(A)),this.OC?(g.pc(this.K,"innertubeCommand",this.OC),this.N()):this.select())}hG(){this.K.logClick(this.cancelButton.element);g.EK(this.K,!0);this.cancelCommand&&g.pc(this.K,"innertubeCommand",this.cancelCommand)}onVideoDataChange(A,
P){b7T(this,P);this.cancelCommand=P.getWatchNextResponse()?.playerOverlays?.playerOverlayRenderer?.autoplay?.playerOverlayAutoplayRenderer?.cancelButton?.buttonRenderer?.command}Hy(){var A=this.K.rj();this.uf!==A&&this.ou(A);g0(this);this.K.logVisibility(this.container.element,A);this.K.logVisibility(this.cancelButton.element,A);this.K.logVisibility(this.Y.jH("ytp-autonav-endscreen-link-container"),A);this.K.logVisibility(this.playButton.element,A)}Uv(A){return A.width<400||A.height<459}};var yD=class extends g.W{constructor(A,P){super({C:"div",rM:["html5-endscreen","ytp-player-content",P||"base-endscreen"]});this.created=!1;this.player=A}create(){this.created=!0}destroy(){this.created=!1}A(){return!1}rj(){return!1}OC(){return!1}};var Z7F=class extends g.W{constructor(A){super({C:"div",rM:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},S:[{C:"div",J:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{C:"span",J:"ytp-upnext-top",S:[{C:"span",J:"ytp-upnext-header",R2:"Up Next"},{C:"span",J:"ytp-upnext-title",R2:"{{title}}"},{C:"span",J:"ytp-upnext-author",R2:"{{author}}"}]},{C:"a",J:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{C:"svg",W:{height:"100%",
version:"1.1",viewBox:"0 0 72 72",width:"100%"},S:[{C:"circle",J:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",J:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",J:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",J:"ytp-upnext-bottom",S:[{C:"span",J:"ytp-upnext-cancel"},
{C:"span",J:"ytp-upnext-paused",R2:"Autoplay is paused"}]}]});this.api=A;this.cancelButton=null;this.xi=this.jH("ytp-svg-autoplay-ring");this.A=this.notification=this.Y=this.suggestion=null;this.OC=new g.jp(this.U,5E3,this);this.L=0;var P=this.jH("ytp-upnext-cancel");this.cancelButton=new g.W({C:"button",rM:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},R2:"Cancel"});g.V(this,this.cancelButton);this.cancelButton.listen("click",this.hG,this);this.cancelButton.i8(P);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.V(this,this.OC);this.api.createClientVe(this.element,this,18788);P=this.jH("ytp-upnext-autoplay-icon");this.V(P,"click",this.b8);this.api.createClientVe(P,this,115130);this.Hy();this.V(A,"autonavvisibility",this.Hy);this.V(A,"mdxnowautoplaying",this.eH);this.V(A,"mdxautoplaycanceled",this.ki);g.Cp(this.element,"ytp-upnext-mobile",this.api.G().Y)}U(){this.notification&&(this.OC.stop(),this.UB(this.A),this.A=null,this.notification.close(),
this.notification=null)}Z(A){this.suggestion=A;g.qI(this,A,"hqdefault.jpg")}Hy(){this.ou(this.api.rj());this.api.logVisibility(this.element,this.api.rj());this.api.logVisibility(this.jH("ytp-upnext-autoplay-icon"),this.api.rj());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.rj())}Ce(){window.focus();this.U()}j(A){this.O()||(g.Tg("a11y-announce",`Up Next ${this.suggestion.title}`),this.L=(0,g.N)(),this.Y=new g.jp(()=>{kL(this,A)},25),kL(this,A),XwF(this.api,O7t(this,
A)));
g.Zn(this.element,"ytp-upnext-autoplay-paused")}hide(){super.hide()}O(){return!!this.Y}isCasting(){return this.api.getPresentingPlayerType()===3}D(){this.N();this.L=(0,g.N)();kL(this);g.mR(this.element,"ytp-upnext-autoplay-paused")}N(){this.O()&&(this.Y.dispose(),this.Y=null)}select(A=!1){if(this.api.G().B("autonav_notifications")&&A&&window.Notification&&typeof document.hasFocus==="function"){let P=Notification.permission;P==="default"?Notification.requestPermission():P!=="granted"||document.hasFocus()||
(this.U(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.xB()}),this.A=this.V(this.notification,"click",this.Ce),this.OC.start())}this.N();this.api.nextVideo(!1,A)}b8(A){!g.k6(this.cancelButton.element,A.target)&&g.eh(A,this.api)&&(this.api.rj()&&this.api.logClick(this.jH("ytp-upnext-autoplay-icon")),this.select())}hG(){this.api.rj()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.EK(this.api,!0)}eH(A){this.isCasting();this.show();
this.j(A)}ki(){this.isCasting();this.N();this.hide()}Nd(){this.N();this.U();super.Nd()}};var zQK=class extends yD{constructor(A){super(A,"videowall-endscreen");this.K=A;this.stills=[];this.D=this.videoData=null;this.j=this.Z=!1;this.Hy=null;g.mR(this.element,"modern-videowall-endscreen");this.Y=new g.R9(this);g.V(this,this.Y);this.U=new g.jp(()=>{g.mR(this.element,"ytp-show-tiles")},0);
g.V(this,this.U);this.table=new g.mE({C:"div",J:"ytp-modern-endscreen-content"});g.V(this,this.table);this.table.i8(this.element);A.getVideoData().jZ?this.O=new tR(A):this.O=new Z7F(A);g.V(this,this.O);g.Jg(this.player,this.O.element,4);A.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var A=this.player.getVideoData();A&&(this.videoData=A);this.N();this.Y.V(this.player,"appresize",this.N);this.Y.V(this.player,"onVideoAreaChange",this.N);this.Y.V(this.player,"videodatachange",
this.onVideoDataChange);this.Y.V(this.player,"autonavchange",this.L);this.Y.V(this.player,"onAutonavCancelled",this.hG);A=this.videoData.autonavState;A!==this.Hy&&this.L(A,!1);this.Y.V(this.element,"transitionend",this.b8)}destroy(){this.Y.Y();g.yu(this.stills);this.stills=[];super.destroy();g.Zn(this.element,"ytp-show-tiles");this.U.stop();this.Hy=this.videoData.autonavState}A(){return this.videoData?.sB||this.videoData.autonavState!==1}show(){var A=this.uf;super.show();g.Zn(this.element,"ytp-show-tiles");
this.player.G().Y?g.XH(this.U):this.U.start();(this.j||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.EK(this.player,!1);lp(this)?(QD(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||nxT(this.player.Y7())&&this.player.B("web_player_pip_logging_fix")?this.O.select(!0):this.O.j():this.videoData.autonavState===3&&this.O.D()):(g.EK(this.player,!0),QD(this));A!==this.uf&&this.player.logVisibility(this.element,!0)}hide(){var A=this.uf;super.hide();this.O.D();QD(this);
A!==this.uf&&this.player.logVisibility(this.element,!1)}b8(A){A.target===this.element&&this.N()}N(){var A=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.Yi()];if(A.length){var P=this.K.RZ(!0,this.K.isFullscreen()),D=Math.floor((P.width-64+16)/(g.j5(P.width*.27,250,450)+16));P=Math.min(3,Math.floor((P.height-64)/((P.width-64-(D-1)*16)/D*.5625+70)));g.z0(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.mR(this.element,`ytp-modern-endscreen-limit-rows-${P}`);g.Cp(this.element,"ytp-modern-endscreen-single-item",D===1);g.Cp(this.element,"ytp-modern-endscreen-row-0",P===0);D=this.table.element;D.ariaLive="polite";this.O.Z(this.videoData.Yi());this.O instanceof tR&&g0(this.O);g.Cp(this.element,"ytp-endscreen-takeover",lp(this));QD(this);P=0;D.ariaBusy="true";var d=A.length;for(let u=0;u<d;u++){let B=u%d,U=this.stills[u];U||(U=new g.fMt(this.player),this.stills[u]=U,D.appendChild(U.element));g.xIJ(U,
A[B]);P++}this.stills.length=P}}onVideoDataChange(){var A=this.player.getVideoData({playerType:1});this.videoData!==A&&(A?.Yi()?(this.videoData=A,this.N()):this.player.F9("missg",{vid:A?.videoId||"",cpn:A?.clientPlaybackNonce||""}))}OC(){return this.O.O()}L(A,P=!1){var D=this.videoData?.sB;if(A===1){if(!D||P)this.j=!1,this.D=this.videoData.clientPlaybackNonce;this.O.N();this.uf&&this.N()}else this.j=!0,this.uf&&lp(this)&&(A===2?this.O.j():A===3&&this.O.D())}hG(A){if(A){for(A=0;A<this.stills.length;A++)this.K.logVisibility(this.stills[A].element,
!0);this.L(1,!0)}else this.D=null,this.j=!1;this.N()}rj(){return this.uf&&lp(this)}};var CVq=class extends g.W{constructor(A){var P=A.G(),D=g.qu||g.C3?{style:"will-change: opacity"}:void 0,d=P.N,u=["ytp-videowall-still"];P.Y&&u.push("ytp-videowall-show-text");super({C:"a",rM:u,W:{href:"{{url}}",target:d?P.Yi:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{C:"div",J:"ytp-videowall-still-image",W:{style:"{{background}}"}},{C:"span",J:"ytp-videowall-still-info",W:{"aria-hidden":"true"},S:[{C:"span",J:"ytp-videowall-still-info-bg",
S:[{C:"span",J:"ytp-videowall-still-info-content",W:D,S:[{C:"span",J:"ytp-videowall-still-info-title",R2:"{{title}}"},{C:"span",J:"ytp-videowall-still-info-author",R2:"{{author_and_views}}"},{C:"span",J:"ytp-videowall-still-info-live",R2:"Live"},{C:"span",J:"ytp-videowall-still-info-duration",R2:"{{duration}}"}]}]}]},{C:"span",rM:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},S:[{C:"span",J:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",
J:"ytp-videowall-still-listlabel-length",S:[" (",{C:"span",R2:"{{playlist_length}}"},")"]}]},{C:"span",rM:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},S:[{C:"span",J:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{C:"span",J:"ytp-videowall-still-listlabel-length",R2:" (50+)"}]}]});this.suggestion=null;this.Y=d;this.api=A;this.O=new g.R9(this);g.V(this,this.O);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.O.V(A,"videodatachange",
this.onVideoDataChange);A.createServerVe(this.element,this);this.onVideoDataChange()}select(){this.api.Iw(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.M9||void 0)&&this.api.logClick(this.element)}onClick(A){if(g.Hp(this.api.G())&&this.api.B("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);let P=this.suggestion.LN(),D={};g.T9(this.api,D);P=g.nS(P,D);g.HD(P,this.api,A)}else g.eh(A,this.api,
this.Y,this.suggestion.sessionData||void 0)&&this.select()}onKeyPress(A){switch(A.keyCode){case 13:case 32:A.defaultPrevented||(this.select(),A.preventDefault())}}onVideoDataChange(){var A=this.api.getVideoData(),P=this.api.G();this.Y=A.OE?!1:P.N}};var ExJ=class extends yD{constructor(A){super(A,"videowall-endscreen");this.K=A;this.D=0;this.stills=[];this.j=this.videoData=null;this.U=this.Hy=!1;this.hG=null;this.N=new g.R9(this);g.V(this,this.N);this.L=new g.jp(()=>{g.mR(this.element,"ytp-show-tiles")},0);
g.V(this,this.L);var P=new g.W({C:"button",rM:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},S:[g.Dg()]});g.V(this,P);P.i8(this.element);P.listen("click",this.eH,this);this.table=new g.mE({C:"div",J:"ytp-endscreen-content"});g.V(this,this.table);this.table.i8(this.element);P=new g.W({C:"button",rM:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},S:[g.d2()]});g.V(this,P);P.i8(this.element);P.listen("click",this.xi,this);A.getVideoData().jZ?this.O=new tR(A):this.O=new Z7F(A);
g.V(this,this.O);g.Jg(this.player,this.O.element,4);A.createClientVe(this.element,this,158789);this.hide()}create(){super.create();var A=this.player.getVideoData();A&&(this.videoData=A);this.Y();this.N.V(this.player,"appresize",this.Y);this.N.V(this.player,"onVideoAreaChange",this.Y);this.N.V(this.player,"videodatachange",this.onVideoDataChange);this.N.V(this.player,"autonavchange",this.Z);this.N.V(this.player,"onAutonavCancelled",this.b8);A=this.videoData.autonavState;A!==this.hG&&this.Z(A,!1);this.N.V(this.element,
"transitionend",this.ki)}destroy(){this.N.Y();g.yu(this.stills);this.stills=[];super.destroy();g.Zn(this.element,"ytp-show-tiles");this.L.stop();this.hG=this.videoData.autonavState}A(){return this.videoData?.sB||this.videoData?.autonavState!==1}show(){var A=this.uf;super.show();g.Zn(this.element,"ytp-show-tiles");this.player.G().Y?g.XH(this.L):this.L.start();(this.U||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.EK(this.player,!1);vA(this)?(Kq(this),this.videoData.autonavState===2?this.player.getVisibilityState()===
3||nxT(this.player.Y7())&&this.player.B("web_player_pip_logging_fix")?this.O.select(!0):this.O.j():this.videoData.autonavState===3&&this.O.D()):(g.EK(this.player,!0),Kq(this));A!==this.uf&&this.player.logVisibility(this.element,!0)}hide(){var A=this.uf;super.hide();this.O.D();Kq(this);A!==this.uf&&this.player.logVisibility(this.element,!1)}ki(A){A.target===this.element&&this.Y()}Y(){var A=this.videoData?.suggestions?.length?this.videoData?.suggestions:[this.videoData?.Yi()];if(A.length){g.mR(this.element,
"ytp-endscreen-paginate");var P=this.K.RZ(!0,this.K.isFullscreen()),D=g.OK(this.K);D&&(D=D.n_()?48:32,P.width-=D*2);var d=P.width/P.height,u=96/54,B=D=2,U=Math.max(P.width/96,2),c=Math.max(P.height/54,2),e=A.length;var H=e*4;for(H-=4;H>0&&(D<U||B<c);){var k=D/2,l=B/2,Q=D<=U-2&&H>=l*4,v=B<=c-2&&H>=k*4;if((k+1)/l*u/d>d/(k/(l+1)*u)&&v)H-=k*4,B+=2;else if(Q)H-=l*4,D+=2;else if(v)H-=k*4,B+=2;else break}u=!1;H>=12&&e*4-H<=6&&(B>=4||D>=4)&&(u=!0);H=D*96;U=B*54;d=H/U<d?P.height/U:P.width/H;d=Math.min(d,2);
H=Math.floor(Math.min(P.width,H*d));U=Math.floor(Math.min(P.height,U*d));P=this.table.element;P.ariaLive="polite";g.s2(P,H,U);g.Fs(P,{marginLeft:`${H/-2}px`,marginTop:`${U/-2}px`});this.O.Z(this.videoData.Yi());this.O instanceof tR&&g0(this.O);g.Cp(this.element,"ytp-endscreen-takeover",vA(this));Kq(this);H+=4;U+=4;d=0;P.ariaBusy="true";for(c=0;c<D;c++)for(k=0;k<B;k++)if(Q=d,v=0,u&&c>=D-2&&k>=B-2?v=1:k%2===0&&c%2===0&&(k<2&&c<2?k===0&&c===0&&(v=2):v=2),Q=g.Mf(Q+this.D,e),v!==0){l=this.stills[d];l||
(l=new CVq(this.player),this.stills[d]=l,P.appendChild(l.element));var R=Math.floor(U*k/B);let p=Math.floor(H*c/D),b=Math.floor(U*(k+v)/B)-R-4,F=Math.floor(H*(c+v)/D)-p-4;g.Y6(l.element,p,R);g.s2(l.element,F,b);g.Fs(l.element,"transitionDelay",(k+c)/20+"s");g.Cp(l.element,"ytp-videowall-still-mini",v===1);g.Cp(l.element,"ytp-videowall-still-large",v>2);v=Math.max(F,b);g.Cp(l.element,"ytp-videowall-still-round-large",v>=256);g.Cp(l.element,"ytp-videowall-still-round-medium",v>96&&v<256);g.Cp(l.element,
"ytp-videowall-still-round-small",v<=96);Q=A[Q];l.suggestion!==Q&&(l.suggestion=Q,v=l.api.G(),R=g.FH(l.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.qI(l,Q,R),g.Hp(v)&&!l.api.B("web_player_log_click_before_generating_ve_conversion_params")&&(v=Q.LN(),R={},g.ML(l.api,"addEmbedsConversionTrackingParams",[R]),v=g.nS(v,R),l.updateValue("url",v)),(Q=(Q=Q.sessionData)&&Q.itct)&&l.api.setTrackingParams(l.element,Q));d++}P.ariaBusy="false";g.Cp(this.element,"ytp-endscreen-paginate",
d<e);for(A=this.stills.length-1;A>=d;A--)D=this.stills[A],g.gE(D.element),g.t4(D);this.stills.length=d}}onVideoDataChange(){var A=this.player.getVideoData({playerType:1});this.videoData!==A&&(A?.Yi()?(this.D=0,this.videoData=A,this.Y()):this.player.F9("missg",{vid:A?.videoId||"",cpn:A?.clientPlaybackNonce||""}))}xi(){this.D+=this.stills.length;this.Y()}eH(){this.D-=this.stills.length;this.Y()}OC(){return this.O.O()}Z(A,P=!1){var D=this.videoData?.sB;if(A===1){if(!D||P)this.U=!1,this.j=this.videoData.clientPlaybackNonce;
this.O.N();this.uf&&this.Y()}else this.U=!0,this.uf&&vA(this)&&(A===2?this.O.j():A===3&&this.O.D())}b8(A){if(A){for(A=0;A<this.stills.length;A++)this.K.logVisibility(this.stills[A].element,!0);this.Z(1,!0)}else this.j=null,this.U=!1;this.Y()}rj(){return this.uf&&vA(this)}};var rsb=class extends g.W{constructor(A){super({C:"button",rM:["ytp-watch-on-youtube-button","ytp-button"],R2:"{{content}}"});this.K=A;this.buttonType=this.buttonType=1;this.O();this.buttonType===2&&g.mR(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.O);this.ou(!0)}O(){switch(this.buttonType){case 1:var A="Watch again on YouTube";var P=156915;break;case 2:A="Continue watching on YouTube";P=156942;break;default:A="Continue watching on YouTube",
P=156942}this.update({content:A});this.K.hasVe(this.element)&&this.K.destroyVe(this.element);this.K.createClientVe(this.element,this,P)}onClick(A){this.K.B("web_player_log_click_before_generating_ve_conversion_params")&&this.K.logClick(this.element);g.HD(this.getVideoUrl(),this.K,A);this.K.B("web_player_log_click_before_generating_ve_conversion_params")||this.K.logClick(this.element)}getVideoUrl(){var A=!0;switch(this.buttonType){case 1:A=!0;break;case 2:A=!1}A=this.K.getVideoUrl(A,!1,!1,!0);var P=
this.K.G();if(g.Hp(P)){let D={};g.Hp(P)&&g.ML(this.K,"addEmbedsConversionTrackingParams",[D]);A=g.nS(A,D)}return A}logVisibility(){this.K.logVisibility(this.element,this.uf&&this.Yi)}show(){super.show();this.logVisibility()}hide(){super.hide();this.logVisibility()}uo(A){super.uo(A);this.logVisibility()}};var YnR=class extends yD{constructor(A){super(A,"watch-again-on-youtube-endscreen");this.watchButton=new rsb(A);g.V(this,this.watchButton);this.watchButton.i8(this.element);g.Gy6(A)&&(this.O=new g.nsT(A),g.V(this,this.O),this.Y=new g.W({C:"div",rM:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},S:[this.O]}),g.V(this,this.Y),this.O.i8(this.Y.element),this.Y.i8(this.element));A.createClientVe(this.element,this,156914);this.hide()}hasSuggestions(){return this.O?.hasSuggestions()}show(){if(this.player.getPlayerState()!==
3){super.show();let P=this.Y;if(P){var A=this.O.hasSuggestions();g.Cp(this.element,"ytp-shorts-branded-ui",A);A?P.show():P.hide()}g.OK(this.player)?.oI(!0);this.player.logVisibility(this.element,!0);this.watchButton.uo(!0)}}hide(){super.hide();g.OK(this.player)?.oI(!1);this.player.logVisibility(this.element,!1);this.watchButton.uo(!1)}};g.H4("endscreen",class extends g.zy{constructor(A){super(A);this.endScreen=null;this.O=this.Y=!1;this.listeners=new g.R9(this);g.V(this,this.listeners);var P=A.G();A.isEmbedsShortsMode()?this.endScreen=new YnR(A):F8F(A)?(this.Y=!0,m9y(this),P.B("delhi_modern_endscreen")?this.endScreen=new zQK(A):this.endScreen=new ExJ(A)):this.endScreen=new yD(A);g.V(this,this.endScreen);g.Jg(A,this.endScreen.element,4);oxx(this);this.listeners.V(A,"videodatachange",this.onVideoDataChange,this);this.listeners.V(A,
g.is("endscreen"),D=>{this.onCueRangeEnter(D)});
this.listeners.V(A,g.Hk("endscreen"),D=>{this.onCueRangeExit(D)})}Lc(){var A=this.player.getVideoData(),P=A.mutedAutoplay&&(A.limitedPlaybackDurationInSeconds>0||A.endSeconds>0||A.mutedAutoplayDurationMode!==2);
if(this.player.isEmbedsShortsMode()&&!P)return!0;var D=!(!A?.Yi()&&!A?.suggestions?.length);D=!F8F(this.player)||D;var d=A.Sx,u=this.player.ZO();return(D||!!A?.sB)&&!d&&!u&&!P}rj(){return this.endScreen.rj()}Y5(){return this.rj()?this.endScreen.OC():!1}Nd(){this.player.kX("endscreen");super.Nd()}load(){{let D=this.player.getVideoData(),d=D.transitionEndpointAtEndOfStream;if(d&&d.videoId){var A=this.player.qs().R_.get("heartbeat");var P=D.Yi();!P||d.videoId!==P.videoId||D.GF?(this.player.Iw(d.videoId,
void 0,void 0,!0,!0,d),A&&A.c9("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),A=!0):A=!1}else A=!1}A||(super.load(),this.endScreen.show())}unload(){super.unload();this.endScreen.hide();this.endScreen.destroy()}onCueRangeEnter(A){this.Lc()&&(this.endScreen.created||this.endScreen.create(),A.getId()==="load"&&this.load())}onCueRangeExit(A){A.getId()==="load"&&this.loaded&&this.unload()}onVideoDataChange(){oxx(this);this.Y&&m9y(this)&&
(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.endScreen=new ExJ(this.player),g.V(this,this.endScreen),g.Jg(this.player,this.endScreen.element,4))}});})(_yt_player);
